souffle: souffle::RemoveEmptyRelationsTransformer Class Reference
souffle::RemoveEmptyRelationsTransformer Class Reference
Transformation pass to remove all empty relations and rules that use empty relations.
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Static Public Member Functions
static bool removeEmptyRelations (AstTranslationUnit &translationUnit)
Eliminate all empty relations (and their uses) in the given program.
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static bool removeEmptyRelationUses (AstTranslationUnit &translationUnit, AstRelation *emptyRelation)
Eliminate rules that contain empty relations and/or rewrite them.
Detailed Description
Transformation pass to remove all empty relations and rules that use empty relations.
Definition at line 185 of file AstTransforms.h.
Member Function Documentation
getName()
std::string souffle::RemoveEmptyRelationsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 187 of file AstTransforms.h.
{
         return "RemoveEmptyRelationsTransformer";
     }
removeEmptyRelations()
bool souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations (AstTranslationUnit & translationUnit) static
Eliminate all empty relations (and their uses) in the given program.
Parameters
translationUnit the program to be processed
Returns
whether the program was modified
Definition at line 533 of file AstTransforms.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::getAtomRelation(), souffle::AstAggregator::getBodyLiterals(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), souffle::AstProgram::removeRelation(), and souffle::visitDepthFirst().
{
     AstProgram& program = *translationUnit.getProgram();
     auto* ioTypes = translationUnit.getAnalysis<IOType>();
     bool changed = false;
     for (auto rel : program.getRelations()) {
         if (!getClauses(program, *rel).empty() || ioTypes->isInput(rel)) {
             continue;
         }
         changed |= removeEmptyRelationUses(translationUnit, rel);
         bool usedInAggregate = false;
         visitDepthFirst(program, [&](const AstAggregator& agg) {
             for (const auto lit : agg.getBodyLiterals()) {
                 visitDepthFirst(*lit, [&](const AstAtom& atom) {
                     if (getAtomRelation(&atom, &program) == rel) {
                         usedInAggregate = true;
                     }
                 });
             }
         });
         if (!usedInAggregate && !ioTypes->isOutput(rel)) {
             program.removeRelation(rel->getQualifiedName());
             changed = true;
         }
     }
     return changed;
 }
removeEmptyRelationUses()
bool souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses (AstTranslationUnit & translationUnit, AstRelation * emptyRelation) static private
Eliminate rules that contain empty relations and/or rewrite them.
Parameters
translationUnit the program to be processed
emptyRelation relation that is empty
Returns
whether the program was modified
Definition at line 562 of file AstTransforms.cpp.
References souffle::AstProgram::addClause(), clauses, souffle::cloneHead(), souffle::getAtomRelation(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::removeClause(), and souffle::visitDepthFirst().
{
     AstProgram& program = *translationUnit.getProgram();
     bool changed = false;
     //
     // (1) drop rules from the program that have empty relations in their bodies.
     // (2) drop negations of empty relations
     //
     // get all clauses
     std::vector<const AstClause*> clauses;
     visitDepthFirst(program, [&](const AstClause& cur) { clauses.push_back(&cur); });
     // clean all clauses
     for (const AstClause* cl : clauses) {
         // check for an atom whose relation is the empty relation
         bool removed = false;
         for (AstLiteral* lit : cl->getBodyLiterals()) {
             if (auto* arg = dynamic_cast<AstAtom*>(lit)) {
                 if (getAtomRelation(arg, &program) == emptyRelation) {
                     program.removeClause(cl);
                     removed = true;
                     changed = true;
                     break;
                 }
             }
         }
         if (!removed) {
             // check whether a negation with empty relations exists
             bool rewrite = false;
             for (AstLiteral* lit : cl->getBodyLiterals()) {
                 if (auto* neg = dynamic_cast<AstNegation*>(lit)) {
                     if (getAtomRelation(neg->getAtom(), &program) == emptyRelation) {
                         rewrite = true;
                         break;
                     }
                 }
             }
             if (rewrite) {
                 // clone clause without negation for empty relations
                 auto res = std::unique_ptr<AstClause>(cloneHead(cl));
                 for (AstLiteral* lit : cl->getBodyLiterals()) {
                     if (auto* neg = dynamic_cast<AstNegation*>(lit)) {
                         if (getAtomRelation(neg->getAtom(), &program) != emptyRelation) {
                             res->addToBody(std::unique_ptr<AstLiteral>(lit->clone()));
                         }
                     } else {
                         res->addToBody(std::unique_ptr<AstLiteral>(lit->clone()));
                     }
                 }
                 program.removeClause(cl);
                 program.addClause(std::move(res));
                 changed = true;
             }
         }
     }
     return changed;
 }
transform()
bool souffle::RemoveEmptyRelationsTransformer::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 200 of file AstTransforms.h.
{
         return removeEmptyRelations(translationUnit);
     }
The documentation for this class was generated from the following files:
AstTransforms.h
AstTransforms.cpp