souffle: souffle::AstTranslator Class Reference
souffle::AstTranslator Class Reference
Main class for AST Translator.
#include <AstTranslator.h>
Data Structures
class ClauseTranslator
translate AST clause to RAM code
struct Location
Concrete attribute.
class ProvenanceClauseTranslator
class ValueIndex
A class indexing the location of variables and record references within a loop nest resulting from the conversion of a rule.
Public Member Functions
AstTranslator ()=default
std::unique_ptr< RamTranslationUnit > translateUnit (AstTranslationUnit &tu)
translates AST to translation unit
Private Member Functions
std::unique_ptr< RamRelationReference > createRelationReference (const std::string name)
create a reference to a RAM relation
RamDomain getConstantRamRepresentation (const AstConstant &constant)
Get ram representation of constant.
size_t getEvaluationArity (const AstAtom *atom) const
determine the auxiliary for relations
std::vector< std::map< std::string, std::string > > getInputDirectives (const AstRelation *rel, std::string filePath=std::string(), const std::string &fileExt=std::string())
std::vector< std::map< std::string, std::string > > getOutputDirectives (const AstRelation *rel, std::string filePath=std::string(), const std::string &fileExt=std::string())
const Json getRecordsTypes ()
Get ram records types.
std::string getRelationName (const AstQualifiedName &id)
converts the given relation identifier into a relation name
SymbolTable & getSymbolTable ()
Return a symbol table.
std::unique_ptr< RamStatement > makeNegationSubproofSubroutine (const AstClause &clause)
translate RAM code for subroutine to get subproofs for non-existence of a tuple
std::unique_ptr< RamStatement > makeSubproofSubroutine (const AstClause &clause)
translate RAM code for subroutine to get subproofs
std::unique_ptr< RamStatement > makeSubproofSubroutineOpt (const AstClause &clause)
translate RAM code for subroutine to get subproofs
void nameUnnamedVariables (AstClause *clause)
assigns names to unnamed variables such that enclosing constructs may be cloned without losing the variable-identity
std::unique_ptr< RamExpression > translateConstant (AstConstant const &c)
translate RAM code for a constant value
std::unique_ptr< RamCondition > translateConstraint (const AstLiteral *arg, const ValueIndex &index)
translate an AST constraint to a RAM condition
std::unique_ptr< RamRelationReference > translateDeltaRelation (const AstRelation *rel)
translate a temporary delta relation to a RAM relation for semi-naive evaluation
void translateDirectives (std::map< std::string, std::string > &directives, const AstRelation *rel, const std::string &filePath, const std::string &fileExt)
translate AST directives to RAM directives
std::unique_ptr< RamRelationReference > translateNewRelation (const AstRelation *rel)
translate a temporary new relation to a RAM relation for semi-naive evaluation
std::unique_ptr< RamStatement > translateNonRecursiveRelation (const AstRelation &rel, const RecursiveClauses *recursiveClauses)
translate RAM code for the non-recursive clauses of the given relation.
void translateProgram (const AstTranslationUnit &translationUnit)
translate AST to RAM Program
std::unique_ptr< RamStatement > translateRecursiveRelation (const std::set< const AstRelation *> &scc, const RecursiveClauses *recursiveClauses)
translate RAM code for recursive relations in a strongly-connected component
std::unique_ptr< RamRelationReference > translateRelation (const AstAtom *atom)
a utility to translate atoms to relations
std::unique_ptr< RamRelationReference > translateRelation (const AstRelation *rel, const std::string relationNamePrefix="")
translate an AST relation to a RAM relation
std::unique_ptr< RamExpression > translateValue (const AstArgument *arg, const ValueIndex &index)
translate an AST argument to a RAM value
Static Private Member Functions
static std::unique_ptr< RamTupleElement > makeRamTupleElement (const Location &loc)
create a RAM element access node
Private Attributes
const AuxiliaryArity * auxArityAnalysis = nullptr
Auxiliary Arity Analysis.
const AstProgram * program = nullptr
AST program.
std::unique_ptr< RamStatement > ramMain
RAM program.
Json RamRecordTypes
Record types information - used in Ram for I/O.
std::map< std::string, std::unique_ptr< RamRelation > > ramRels
RAM relations.
std::map< std::string, std::unique_ptr< RamStatement > > ramSubs
Subroutines.
SymbolTable symbolTable
Symbol Table.
const TypeEnvironment * typeEnv = nullptr
Type environment.
Detailed Description
Main class for AST Translator.
Definition at line 65 of file AstTranslator.h.
Constructor & Destructor Documentation
AstTranslator()
souffle::AstTranslator::AstTranslator () default
Member Function Documentation
createRelationReference()
std::unique_ptr< RamRelationReference > souffle::AstTranslator::createRelationReference (const std::string name) private
create a reference to a RAM relation
Definition at line 261 of file AstTranslator.cpp.
References ramRels, and relation.
Referenced by getRelationName(), and translateRelation().
{
     auto it = ramRels.find(name);
     assert(it != ramRels.end() && "relation name not found");
     const RamRelation* relation = it->second.get();
     return std::make_unique<RamRelationReference>(relation);
 }
getConstantRamRepresentation()
RamDomain souffle::AstTranslator::getConstantRamRepresentation (const AstConstant & constant) inline private
Get ram representation of constant.
Definition at line 404 of file AstTranslator.h.
References souffle::fatal(), souffle::AstNumericConstant::Float, getSymbolTable(), souffle::AstNumericConstant::Int, souffle::SymbolTable::lookup(), makeNegationSubproofSubroutine(), makeSubproofSubroutine(), makeSubproofSubroutineOpt(), souffle::RamFloatFromString(), souffle::RamSignedFromString(), souffle::RamUnsignedFromString(), translateConstant(), translateNonRecursiveRelation(), translateProgram(), translateRecursiveRelation(), and souffle::AstNumericConstant::Uint.
Referenced by translateConstant().
{
         if (auto strConstant = dynamic_cast<const AstStringConstant*>(&constant)) {
             return getSymbolTable().lookup(strConstant->getConstant());
         } else if (dynamic_cast<const AstNilConstant*>(&constant) != nullptr) {
             return 0;
         } else if (auto* numConstant = dynamic_cast<const AstNumericConstant*>(&constant)) {
             assert(numConstant->getType().has_value());
             switch (*numConstant->getType()) {
                 case AstNumericConstant::Type::Int:
                     return RamSignedFromString(numConstant->getConstant(), nullptr, 0);
                 case AstNumericConstant::Type::Uint:
                     return RamUnsignedFromString(numConstant->getConstant(), nullptr, 0);
                 case AstNumericConstant::Type::Float: return RamFloatFromString(numConstant->getConstant());
             }
         }
         fatal("unaccounted-for constant");
     }
getEvaluationArity()
size_t souffle::AstTranslator::getEvaluationArity (const AstAtom * atom) const private
determine the auxiliary for relations
Definition at line 87 of file AstTranslator.cpp.
References auxArityAnalysis, souffle::AuxiliaryArity::getArity(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), program, and souffle::AstQualifiedName::toString().
Referenced by translateConstraint().
{
     if (atom->getQualifiedName().toString().find("@delta_") == 0) {
         const AstQualifiedName& originalRel = AstQualifiedName(atom->getQualifiedName().toString().substr(7));
         return auxArityAnalysis->getArity(getRelation(*program, originalRel));
     } else if (atom->getQualifiedName().toString().find("@new_") == 0) {
         const AstQualifiedName& originalRel = AstQualifiedName(atom->getQualifiedName().toString().substr(5));
         return auxArityAnalysis->getArity(getRelation(*program, originalRel));
     } else if (atom->getQualifiedName().toString().find("@info_") == 0) {
         return 0;
     } else {
         return auxArityAnalysis->getArity(atom);
     }
 }
getInputDirectives()
std::vector< std::map< std::string, std::string > > souffle::AstTranslator::getInputDirectives (const AstRelation * rel, std::string filePath = std::string(), const std::string & fileExt = std::string()) private
Definition at line 150 of file AstTranslator.cpp.
References souffle::Global::config(), souffle::AstProgram::getIOs(), souffle::AstRelation::getQualifiedName(), souffle::input, program, translateDirectives(), and souffle::unescape().
Referenced by getRelationName(), and translateProgram().
{
     std::vector<std::map<std::string, std::string>> inputDirectives;
     std::vector<const AstIO*> relLoads;
     for (const auto* io : program->getIOs()) {
         if (io->getQualifiedName() == rel->getQualifiedName() && io->getType() == AstIoType::input) {
             relLoads.push_back(io);
         }
     }
     for (const auto& current : relLoads) {
         std::map<std::string, std::string> directives;
         for (const auto& currentPair : current->getDirectives()) {
             directives.insert(std::make_pair(currentPair.first, unescape(currentPair.second)));
         }
         directives["operation"] = "input";
         inputDirectives.push_back(directives);
     }
     if (inputDirectives.empty()) {
         inputDirectives.emplace_back();
     }
     const std::string inputFilePath = (filePath.empty()) ? Global::config().get("fact-dir") : filePath;
     const std::string inputFileExt = (fileExt.empty()) ? ".facts" : fileExt;
     for (auto& directives : inputDirectives) {
         translateDirectives(directives, rel, inputFilePath, inputFileExt);
     }
     return inputDirectives;
 }
getOutputDirectives()
std::vector< std::map< std::string, std::string > > souffle::AstTranslator::getOutputDirectives (const AstRelation * rel, std::string filePath = std::string(), const std::string & fileExt = std::string()) private
Definition at line 183 of file AstTranslator.cpp.
References auxArityAnalysis, souffle::Global::config(), souffle::AuxiliaryArity::getArity(), souffle::AstRelation::getAttributes(), souffle::AstProgram::getIOs(), souffle::AstRelation::getQualifiedName(), souffle::join(), souffle::output, souffle::printsize, program, souffle::toString(), translateDirectives(), and souffle::unescape().
Referenced by getRelationName(), and translateProgram().
{
     std::vector<std::map<std::string, std::string>> outputDirectives;
     std::vector<const AstIO*> relStores;
     for (const auto* store : program->getIOs()) {
         if (store->getQualifiedName() == rel->getQualifiedName() &&
                 (store->getType() == AstIoType::output || store->getType() == AstIoType::printsize)) {
             relStores.push_back(store);
         }
     }
     // If stdout is requested then remove all directives from the datalog file.
     if (Global::config().get("output-dir") == "-") {
         bool hasOutput = false;
         for (const auto* current : relStores) {
             std::map<std::string, std::string> directives;
             if (current->getType() == AstIoType::printsize) {
                 directives["operation"] = "printsize";
                 directives["IO"] = "stdoutprintsize";
                 outputDirectives.push_back(directives);
             } else if (!hasOutput) {
                 hasOutput = true;
                 directives["IO"] = "stdout";
                 directives["headers"] = "true";
                 directives["operation"] = "output";
                 outputDirectives.push_back(directives);
             }
         }
     } else {
         for (const auto* current : relStores) {
             std::map<std::string, std::string> directives;
             for (const auto& currentPair : current->getDirectives()) {
                 directives.insert(std::make_pair(currentPair.first, unescape(currentPair.second)));
             }
             if (current->getType() == AstIoType::printsize) {
                 directives["operation"] = "printsize";
                 directives["IO"] = "stdoutprintsize";
             } else {
                 directives["operation"] = "output";
             }
             outputDirectives.push_back(directives);
         }
     }
     if (outputDirectives.empty()) {
         outputDirectives.emplace_back();
     }
     const std::string outputFilePath = (filePath.empty()) ? Global::config().get("output-dir") : filePath;
     const std::string outputFileExt = (fileExt.empty()) ? ".csv" : fileExt;
     for (auto& directives : outputDirectives) {
         translateDirectives(directives, rel, outputFilePath, outputFileExt);
         if (directives.find("attributeNames") == directives.end()) {
             std::string delimiter("\t");
             if (directives.find("delimiter") != directives.end()) {
                 delimiter = directives.at("delimiter");
             }
             std::vector<std::string> attributeNames;
             for (const auto* attribute : rel->getAttributes()) {
                 attributeNames.push_back(attribute->getName());
             }
             if (Global::config().has("provenance")) {
                 std::vector<std::string> originalAttributeNames(
                         attributeNames.begin(), attributeNames.end() - auxArityAnalysis->getArity(rel));
                 directives["attributeNames"] = toString(join(originalAttributeNames, delimiter));
             } else {
                 directives["attributeNames"] = toString(join(attributeNames, delimiter));
             }
         }
     }
     return outputDirectives;
 }
getRecordsTypes()
const Json souffle::AstTranslator::getRecordsTypes () private
Get ram records types.
If they don't exists - create them.
Definition at line 1723 of file AstTranslator.cpp.
References souffle::TypeEnvironment::getType(), souffle::getTypeQualifier(), souffle::AstProgram::getTypes(), json11::Json::is_null(), program, RamRecordTypes, and typeEnv.
Referenced by souffle::AstTranslator::ProvenanceClauseTranslator::ProvenanceClauseTranslator(), and translateDirectives().
{
     // Check if the types where already constructed
     if (!RamRecordTypes.is_null()) {
         return RamRecordTypes;
     }
     std::vector<std::string> elementTypes;
     std::map<std::string, Json> records;
     // Iterate over all record types in the program populating the records map.
     for (auto* astType : program->getTypes()) {
         const auto& type = typeEnv->getType(astType->getQualifiedName());
         if (isA<RecordType>(type)) {
             elementTypes.clear();
             for (const Type* field : as<RecordType>(type)->getFields()) {
                 elementTypes.push_back(getTypeQualifier(*field));
             }
             const size_t recordArity = elementTypes.size();
             Json recordInfo = Json::object{
                     {"types", std::move(elementTypes)}, {"arity", static_cast<long long>(recordArity)}};
             records.emplace(getTypeQualifier(type), std::move(recordInfo));
         }
     }
     RamRecordTypes = Json(records);
     return RamRecordTypes;
 }
getRelationName()
std::string souffle::AstTranslator::getRelationName (const AstQualifiedName & id) inline private
converts the given relation identifier into a relation name
Definition at line 295 of file AstTranslator.h.
References createRelationReference(), getInputDirectives(), getOutputDirectives(), souffle::join(), souffle::toString(), translateConstraint(), translateDeltaRelation(), translateDirectives(), translateNewRelation(), translateRelation(), and translateValue().
Referenced by translateDirectives(), and translateRelation().
{
         return toString(join(id.getQualifiers(), "."));
     }
getSymbolTable()
SymbolTable& souffle::AstTranslator::getSymbolTable () inline private
Return a symbol table.
Definition at line 397 of file AstTranslator.h.
References symbolTable.
Referenced by getConstantRamRepresentation(), translateUnit(), and translateValue().
{
         return symbolTable;
     }
makeNegationSubproofSubroutine()
std::unique_ptr< RamStatement > souffle::AstTranslator::makeNegationSubproofSubroutine (const AstClause & clause) private
translate RAM code for subroutine to get subproofs for non-existence of a tuple
make a subroutine to search for subproofs for the non-existence of a tuple
Definition at line 1372 of file AstTranslator.cpp.
References souffle::appendStmt(), auxArityAnalysis, souffle::AstClause::clone(), souffle::AuxiliaryArity::getArity(), souffle::AstVariable::getName(), i, translateConstraint(), translateRelation(), translateValue(), and souffle::visitDepthFirst().
Referenced by getConstantRamRepresentation(), and translateProgram().
{
     // TODO (taipan-snake): Currently we only deal with atoms (no constraints or negations or aggregates
     // or anything else...)
     //
     // The resulting subroutine looks something like this:
     // IF (arg(0), arg(1), _, _) IN rel_1:
     //   return 1
     // IF (arg(0), arg(1), _ ,_) NOT IN rel_1:
     //   return 0
     // ...
     // clone clause for mutation
     auto clauseReplacedAggregates = std::unique_ptr<AstClause>(clause.clone());
     int aggNumber = 0;
     struct AggregatesToVariables : public AstNodeMapper {
         int& aggNumber;
         AggregatesToVariables(int& aggNumber) : aggNumber(aggNumber) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (dynamic_cast<AstAggregator*>(node.get()) != nullptr) {
                 return std::make_unique<AstVariable>("agg_" + std::to_string(aggNumber++));
             }
             node->apply(*this);
             return node;
         }
     };
     AggregatesToVariables aggToVar(aggNumber);
     clauseReplacedAggregates->apply(aggToVar);
     // build a vector of unique variables
     std::vector<const AstVariable*> uniqueVariables;
     visitDepthFirst(*clauseReplacedAggregates, [&](const AstVariable& var) {
         if (var.getName().find("@level_num") == std::string::npos) {
             // use find_if since uniqueVariables stores pointers, and we need to dereference the pointer to
             // check equality
             if (std::find_if(uniqueVariables.begin(), uniqueVariables.end(),
                         [&](const AstVariable* v) { return *v == var; }) == uniqueVariables.end()) {
                 uniqueVariables.push_back(&var);
             }
         }
     });
     // a mapper to replace variables with subroutine arguments
     struct VariablesToArguments : public AstNodeMapper {
         const std::vector<const AstVariable*>& uniqueVariables;
         VariablesToArguments(const std::vector<const AstVariable*>& uniqueVariables)
                 : uniqueVariables(uniqueVariables) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // replace unknown variables
             if (auto varPtr = dynamic_cast<const AstVariable*>(node.get())) {
                 if (varPtr->getName().find("@level_num") == std::string::npos) {
                     size_t argNum = std::find_if(uniqueVariables.begin(), uniqueVariables.end(),
                                             [&](const AstVariable* v) { return *v == *varPtr; }) -
                                     uniqueVariables.begin();
                     return std::make_unique<AstSubroutineArgument>(argNum);
                 } else {
                     return std::make_unique<AstUnnamedVariable>();
                 }
             }
             // apply recursive
             node->apply(*this);
             // otherwise nothing
             return node;
         }
     };
     // the structure of this subroutine is a sequence where each nested statement is a search in each
     // relation
     std::vector<std::unique_ptr<RamStatement>> searchSequence;
     // make a copy so that when we mutate clause, pointers to objects in newClause are not affected
     auto newClause = std::unique_ptr<AstClause>(clauseReplacedAggregates->clone());
     // go through each body atom and create a return
     size_t litNumber = 0;
     for (const auto& lit : newClause->getBodyLiterals()) {
         if (auto atom = dynamic_cast<AstAtom*>(lit)) {
             size_t auxiliaryArity = auxArityAnalysis->getArity(atom);
             // get a RamRelationReference
             auto relRef = translateRelation(atom);
             // construct a query
             std::vector<std::unique_ptr<RamExpression>> query;
             // translate variables to subroutine arguments
             VariablesToArguments varsToArgs(uniqueVariables);
             atom->apply(varsToArgs);
             auto atomArgs = atom->getArguments();
             // add each value (subroutine argument) to the search query
             for (size_t i = 0; i < atom->getArity() - auxiliaryArity; i++) {
                 auto arg = atomArgs[i];
                 query.push_back(translateValue(arg, ValueIndex()));
             }
             // fill up query with nullptrs for the provenance columns
             for (size_t i = 0; i < auxiliaryArity; i++) {
                 query.push_back(std::make_unique<RamUndefValue>());
             }
             // ensure the length of query tuple is correct
             assert(query.size() == atom->getArity() && "wrong query tuple size");
             // create existence checks to check if the tuple exists or not
             auto existenceCheck = std::make_unique<RamExistenceCheck>(
                     std::unique_ptr<RamRelationReference>(relRef->clone()), std::move(query));
             auto negativeExistenceCheck = std::make_unique<RamNegation>(
                     std::unique_ptr<RamExistenceCheck>(existenceCheck->clone()));
             // return true if the tuple exists
             std::vector<std::unique_ptr<RamExpression>> returnTrue;
             returnTrue.push_back(std::make_unique<RamSignedConstant>(1));
             // return false if the tuple exists
             std::vector<std::unique_ptr<RamExpression>> returnFalse;
             returnFalse.push_back(std::make_unique<RamSignedConstant>(0));
             // create a RamQuery to return true/false
             appendStmt(searchSequence,
                     std::make_unique<RamQuery>(std::make_unique<RamFilter>(std::move(existenceCheck),
                             std::make_unique<RamSubroutineReturn>(std::move(returnTrue)))));
             appendStmt(searchSequence,
                     std::make_unique<RamQuery>(std::make_unique<RamFilter>(std::move(negativeExistenceCheck),
                             std::make_unique<RamSubroutineReturn>(std::move(returnFalse)))));
         } else if (auto con = dynamic_cast<AstConstraint*>(lit)) {
             VariablesToArguments varsToArgs(uniqueVariables);
             con->apply(varsToArgs);
             // translate to a RamCondition
             auto condition = translateConstraint(con, ValueIndex());
             auto negativeCondition =
                     std::make_unique<RamNegation>(std::unique_ptr<RamCondition>(condition->clone()));
             // create a return true value
             std::vector<std::unique_ptr<RamExpression>> returnTrue;
             returnTrue.push_back(std::make_unique<RamSignedConstant>(1));
             // create a return false value
             std::vector<std::unique_ptr<RamExpression>> returnFalse;
             returnFalse.push_back(std::make_unique<RamSignedConstant>(0));
             appendStmt(searchSequence,
                     std::make_unique<RamQuery>(std::make_unique<RamFilter>(std::move(condition),
                             std::make_unique<RamSubroutineReturn>(std::move(returnTrue)))));
             appendStmt(searchSequence,
                     std::make_unique<RamQuery>(std::make_unique<RamFilter>(std::move(negativeCondition),
                             std::make_unique<RamSubroutineReturn>(std::move(returnFalse)))));
         }
         litNumber++;
     }
     return std::make_unique<RamSequence>(std::move(searchSequence));
 }
makeRamTupleElement()
std::unique_ptr< RamTupleElement > souffle::AstTranslator::makeRamTupleElement (const Location & loc) static private
create a RAM element access node
Definition at line 83 of file AstTranslator.cpp.
References souffle::AstTranslator::Location::element, and souffle::AstTranslator::Location::identifier.
Referenced by souffle::AstTranslator::ClauseTranslator::translateClause(), and translateValue().
{
     return std::make_unique<RamTupleElement>(loc.identifier, loc.element);
 }
makeSubproofSubroutine()
std::unique_ptr< RamStatement > souffle::AstTranslator::makeSubproofSubroutine (const AstClause & clause) private
translate RAM code for subroutine to get subproofs
make a subroutine to search for subproofs
Definition at line 1301 of file AstTranslator.cpp.
References auxArityAnalysis, souffle::clone(), souffle::AstClause::clone(), souffle::Global::config(), souffle::EQ, souffle::FEQ, souffle::Float, souffle::AuxiliaryArity::getArity(), i, souffle::LT, nameUnnamedVariables(), and souffle::AstTranslator::ClauseTranslator::translateClause().
Referenced by getConstantRamRepresentation(), and translateProgram().
{
     // make intermediate clause with constraints
     std::unique_ptr<AstClause> intermediateClause(clause.clone());
     // name unnamed variables
     nameUnnamedVariables(intermediateClause.get());
     // add constraint for each argument in head of atom
     AstAtom* head = intermediateClause->getHead();
     size_t auxiliaryArity = auxArityAnalysis->getArity(head);
     auto args = head->getArguments();
     for (size_t i = 0; i < head->getArity() - auxiliaryArity; i++) {
         auto arg = args[i];
         if (auto var = dynamic_cast<AstVariable*>(arg)) {
             // FIXME: float equiv (`FEQ`)
             intermediateClause->addToBody(std::make_unique<AstBinaryConstraint>(BinaryConstraintOp::EQ,
                     std::unique_ptr<AstArgument>(var->clone()), std::make_unique<AstSubroutineArgument>(i)));
         } else if (auto func = dynamic_cast<AstFunctor*>(arg)) {
             auto opEq = func->getReturnType() == TypeAttribute::Float ? BinaryConstraintOp::FEQ
                                                                       : BinaryConstraintOp::EQ;
             intermediateClause->addToBody(std::make_unique<AstBinaryConstraint>(opEq,
                     std::unique_ptr<AstArgument>(func->clone()), std::make_unique<AstSubroutineArgument>(i)));
         } else if (auto rec = dynamic_cast<AstRecordInit*>(arg)) {
             intermediateClause->addToBody(std::make_unique<AstBinaryConstraint>(BinaryConstraintOp::EQ,
                     std::unique_ptr<AstArgument>(rec->clone()), std::make_unique<AstSubroutineArgument>(i)));
         }
     }
     if (Global::config().get("provenance") == "subtreeHeights") {
         // starting index of subtree level arguments in argument list
         // starts immediately after original arguments as height and rulenumber of tuple are not passed to
         // subroutine
         size_t levelIndex = head->getArguments().size() - auxiliaryArity;
         // add level constraints
         const auto& bodyLiterals = intermediateClause->getBodyLiterals();
         for (auto lit : bodyLiterals) {
             if (auto atom = dynamic_cast<AstAtom*>(lit)) {
                 auto arity = atom->getArity();
                 auto auxiliaryArity = auxArityAnalysis->getArity(atom);
                 auto literalLevelIndex = arity - auxiliaryArity + 1;
                 auto atomArgs = atom->getArguments();
                 // FIXME: float equiv (`FEQ`)
                 intermediateClause->addToBody(std::make_unique<AstBinaryConstraint>(BinaryConstraintOp::EQ,
                         std::unique_ptr<AstArgument>(atomArgs[literalLevelIndex]->clone()),
                         std::make_unique<AstSubroutineArgument>(levelIndex)));
             }
             levelIndex++;
         }
     } else {
         // index of level argument in argument list
         size_t levelIndex = head->getArguments().size() - auxiliaryArity;
         // add level constraints
         const auto& bodyLiterals = intermediateClause->getBodyLiterals();
         for (auto lit : bodyLiterals) {
             if (auto atom = dynamic_cast<AstAtom*>(lit)) {
                 auto arity = atom->getArity();
                 auto atomArgs = atom->getArguments();
                 // arity - 1 is the level number in body atoms
                 intermediateClause->addToBody(std::make_unique<AstBinaryConstraint>(BinaryConstraintOp::LT,
                         std::unique_ptr<AstArgument>(atomArgs[arity - 1]->clone()),
                         std::make_unique<AstSubroutineArgument>(levelIndex)));
             }
         }
     }
     return ProvenanceClauseTranslator(*this).translateClause(*intermediateClause, clause);
 }
makeSubproofSubroutineOpt()
std::unique_ptr<RamStatement> souffle::AstTranslator::makeSubproofSubroutineOpt (const AstClause & clause) private
translate RAM code for subroutine to get subproofs
Referenced by getConstantRamRepresentation().
nameUnnamedVariables()
void souffle::AstTranslator::nameUnnamedVariables (AstClause * clause) private
assigns names to unnamed variables such that enclosing constructs may be cloned without losing the variable-identity
A utility function assigning names to unnamed variables such that enclosing constructs may be cloned without losing the variable-identity.
Definition at line 1052 of file AstTranslator.cpp.
References souffle::toString().
Referenced by makeSubproofSubroutine(), and translateRecursiveRelation().
{
     // the node mapper conducting the actual renaming
     struct Instantiator : public AstNodeMapper {
         mutable int counter = 0;
         Instantiator() = default;
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // apply recursive
             node->apply(*this);
             // replace unknown variables
             if (dynamic_cast<AstUnnamedVariable*>(node.get()) != nullptr) {
                 auto name = " _unnamed_var" + toString(++counter);
                 return std::make_unique<AstVariable>(name);
             }
             // otherwise nothing
             return node;
         }
     };
     // name all variables in the atoms
     Instantiator init;
     for (auto& atom : getBodyLiterals<AstAtom>(*clause)) {
         atom->apply(init);
     }
 }
translateConstant()
std::unique_ptr< RamExpression > souffle::AstTranslator::translateConstant (AstConstant const & c) private
translate RAM code for a constant value
Definition at line 966 of file AstTranslator.cpp.
References souffle::AstNumericConstant::Float, getConstantRamRepresentation(), souffle::AstNumericConstant::Int, and souffle::AstNumericConstant::Uint.
Referenced by getConstantRamRepresentation().
{
     auto const rawConstant = getConstantRamRepresentation(c);
     if (auto* const c_num = dynamic_cast<const AstNumericConstant*>(&c)) {
         switch (*c_num->getType()) {
             case AstNumericConstant::Type::Int: return std::make_unique<RamSignedConstant>(rawConstant);
             case AstNumericConstant::Type::Uint: return std::make_unique<RamUnsignedConstant>(rawConstant);
             case AstNumericConstant::Type::Float: return std::make_unique<RamFloatConstant>(rawConstant);
         }
     }
     return std::make_unique<RamSignedConstant>(rawConstant);
 }
translateConstraint()
std::unique_ptr< RamCondition > souffle::AstTranslator::translateConstraint (const AstLiteral * arg, const ValueIndex & index) private
translate an AST constraint to a RAM condition
for atoms
for binary relations
for negations
for provenance negation
Definition at line 387 of file AstTranslator.cpp.
References souffle::Global::config(), souffle::AstNegation::getAtom(), getEvaluationArity(), souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getOperator(), souffle::AstBinaryConstraint::getRHS(), i, translateRelation(), and translateValue().
Referenced by getRelationName(), and makeNegationSubproofSubroutine().
{
     class ConstraintTranslator : public AstVisitor<std::unique_ptr<RamCondition>> {
         AstTranslator& translator;
         const ValueIndex& index;
     public:
         ConstraintTranslator(AstTranslator& translator, const ValueIndex& index)
                 : translator(translator), index(index) {}
         /** for atoms */
         std::unique_ptr<RamCondition> visitAtom(const AstAtom&) override {
             return nullptr;  // covered already within the scan/lookup generation step
         }
         /** for binary relations */
         std::unique_ptr<RamCondition> visitBinaryConstraint(const AstBinaryConstraint& binRel) override {
             std::unique_ptr<RamExpression> valLHS = translator.translateValue(binRel.getLHS(), index);
             std::unique_ptr<RamExpression> valRHS = translator.translateValue(binRel.getRHS(), index);
             return std::make_unique<RamConstraint>(
                     binRel.getOperator(), std::move(valLHS), std::move(valRHS));
         }
         /** for negations */
         std::unique_ptr<RamCondition> visitNegation(const AstNegation& neg) override {
             const auto* atom = neg.getAtom();
             size_t auxiliaryArity = translator.getEvaluationArity(atom);
             assert(auxiliaryArity <= atom->getArity() && "auxiliary arity out of bounds");
             size_t arity = atom->getArity() - auxiliaryArity;
             std::vector<std::unique_ptr<RamExpression>> values;
             auto args = atom->getArguments();
             for (size_t i = 0; i < arity; i++) {
                 values.push_back(translator.translateValue(args[i], index));
             }
             for (size_t i = 0; i < auxiliaryArity; i++) {
                 values.push_back(std::make_unique<RamUndefValue>());
             }
             if (arity > 0) {
                 return std::make_unique<RamNegation>(std::make_unique<RamExistenceCheck>(
                         translator.translateRelation(atom), std::move(values)));
             } else {
                 return std::make_unique<RamEmptinessCheck>(translator.translateRelation(atom));
             }
         }
         /** for provenance negation */
         std::unique_ptr<RamCondition> visitProvenanceNegation(const AstProvenanceNegation& neg) override {
             const auto* atom = neg.getAtom();
             size_t auxiliaryArity = translator.getEvaluationArity(atom);
             assert(auxiliaryArity < atom->getArity() && "auxiliary arity out of bounds");
             size_t arity = atom->getArity() - auxiliaryArity;
             std::vector<std::unique_ptr<RamExpression>> values;
             auto args = atom->getArguments();
             for (size_t i = 0; i < arity; i++) {
                 values.push_back(translator.translateValue(args[i], index));
             }
             // we don't care about the provenance columns when doing the existence check
             if (Global::config().has("provenance")) {
                 // undefined value for rule number
                 values.push_back(std::make_unique<RamUndefValue>());
                 // add the height annotation for provenanceNotExists
                 for (size_t h = 0; h + 1 < auxiliaryArity; h++) {
                     values.push_back(translator.translateValue(args[arity + h + 1], index));
                 }
             }
             return std::make_unique<RamNegation>(std::make_unique<RamProvenanceExistenceCheck>(
                     translator.translateRelation(atom), std::move(values)));
         }
     };
     return ConstraintTranslator(*this, index)(*lit);
 }
translateDeltaRelation()
std::unique_ptr< RamRelationReference > souffle::AstTranslator::translateDeltaRelation (const AstRelation * rel) private
translate a temporary delta relation to a RAM relation for semi-naive evaluation
Definition at line 278 of file AstTranslator.cpp.
References translateRelation().
Referenced by getRelationName(), and translateRecursiveRelation().
{
     return translateRelation(rel, "@delta_");
 }
translateDirectives()
void souffle::AstTranslator::translateDirectives (std::map< std::string, std::string > & directives, const AstRelation * rel, const std::string & filePath, const std::string & fileExt) private
translate AST directives to RAM directives
Definition at line 101 of file AstTranslator.cpp.
References auxArityAnalysis, json11::Json::dump(), souffle::AuxiliaryArity::getArity(), souffle::AstRelation::getArity(), souffle::AstRelation::getAttributes(), souffle::AstRelation::getQualifiedName(), getRecordsTypes(), getRelationName(), souffle::TypeEnvironment::getType(), souffle::getTypeQualifier(), typeEnv, and types.
Referenced by getInputDirectives(), getOutputDirectives(), and getRelationName().
{
     // set relation name correctly
     directives["name"] = getRelationName(rel->getQualifiedName());
     // set a default IO type of file and a default filename if not supplied
     if (directives.find("IO") == directives.end()) {
         directives["IO"] = "file";
     }
     // load intermediate relations from correct files
     if (directives.at("IO") == "file") {
         // set filename by relation if not given
         if (directives.find("filename") == directives.end()) {
             directives["filename"] = directives.at("name") + fileExt;
         }
     }
     // legacy support for SQLite prior to 2020-03-18
     // convert dbname to filename
     if (directives.at("IO") == "sqlite" && directives.find("dbname") != directives.end()) {
         directives["filename"] = directives.at("dbname");
     }
     // if filename is not an absolute path, concat with cmd line facts directory
     if (directives.find("filename") != directives.end() && directives.at("filename").front() != '/') {
         directives["filename"] = filePath + "/" + directives.at("filename");
     }
     // Prepare type system information.
     std::string name = getRelationName(rel->getQualifiedName());
     std::vector<std::string> attributesTypes;
     for (const auto* attribute : rel->getAttributes()) {
         auto type = getTypeQualifier(typeEnv->getType(attribute->getTypeName()));
         attributesTypes.push_back(type);
     }
     // Casting due to json11.h type requirements.
     long long arity{static_cast<long long>(rel->getArity() - auxArityAnalysis->getArity(rel))};
     long long auxArity{static_cast<long long>(auxArityAnalysis->getArity(rel))};
     const Json rec = getRecordsTypes();
     Json relJson = Json::object{{"arity", arity}, {"auxArity", auxArity},
             {"types", Json::array(attributesTypes.begin(), attributesTypes.end())}};
     Json types = Json::object{{name, relJson}, {"records", getRecordsTypes()}};
     directives["types"] = types.dump();
 }
translateNewRelation()
std::unique_ptr< RamRelationReference > souffle::AstTranslator::translateNewRelation (const AstRelation * rel) private
translate a temporary new relation to a RAM relation for semi-naive evaluation
Definition at line 282 of file AstTranslator.cpp.
References translateRelation().
Referenced by getRelationName(), and translateRecursiveRelation().
{
     return translateRelation(rel, "@new_");
 }
translateNonRecursiveRelation()
std::unique_ptr< RamStatement > souffle::AstTranslator::translateNonRecursiveRelation (const AstRelation & rel, const RecursiveClauses * recursiveClauses) private
translate RAM code for the non-recursive clauses of the given relation.
generate RAM code for a non-recursive relation
Returns
a corresponding statement or null if there are no non-recursive clauses.
Definition at line 981 of file AstTranslator.cpp.
References souffle::appendStmt(), souffle::Global::config(), souffle::getClauses(), souffle::AstRelation::getQualifiedName(), souffle::AstNode::getSrcLoc(), souffle::LogStatement::nNonrecursiveRelation(), souffle::LogStatement::nNonrecursiveRule(), program, souffle::RecursiveClauses::recursive(), rule, souffle::stringify(), souffle::LogStatement::tNonrecursiveRelation(), souffle::LogStatement::tNonrecursiveRule(), souffle::toString(), souffle::AstTranslator::ClauseTranslator::translateClause(), and translateRelation().
Referenced by getConstantRamRepresentation(), translateProgram(), and translateRecursiveRelation().
{
     /* start with an empty sequence */
     std::vector<std::unique_ptr<RamStatement>> res;
     // the ram table reference
     std::unique_ptr<RamRelationReference> rrel = translateRelation(&rel);
     /* iterate over all clauses that belong to the relation */
     for (AstClause* clause : getClauses(*program, rel)) {
         // skip recursive rules
         if (recursiveClauses->recursive(clause)) {
             continue;
         }
         // translate clause
         std::unique_ptr<RamStatement> rule = ClauseTranslator(*this).translateClause(*clause, *clause);
         // add logging
         if (Global::config().has("profile")) {
             const std::string& relationName = toString(rel.getQualifiedName());
             const SrcLocation& srcLocation = clause->getSrcLoc();
             const std::string clauseText = stringify(toString(*clause));
             const std::string logTimerStatement =
                     LogStatement::tNonrecursiveRule(relationName, srcLocation, clauseText);
             const std::string logSizeStatement =
                     LogStatement::nNonrecursiveRule(relationName, srcLocation, clauseText);
             rule = std::make_unique<RamLogRelationTimer>(
                     std::move(rule), logTimerStatement, std::unique_ptr<RamRelationReference>(rrel->clone()));
         }
         // add debug info
         std::ostringstream ds;
         ds << toString(*clause) << "\nin file ";
         ds << clause->getSrcLoc();
         rule = std::make_unique<RamDebugInfo>(std::move(rule), ds.str());
         // add rule to result
         appendStmt(res, std::move(rule));
     }
     // add logging for entire relation
     if (Global::config().has("profile")) {
         const std::string& relationName = toString(rel.getQualifiedName());
         const SrcLocation& srcLocation = rel.getSrcLoc();
         const std::string logSizeStatement = LogStatement::nNonrecursiveRelation(relationName, srcLocation);
         // add timer if we did any work
         if (!res.empty()) {
             const std::string logTimerStatement =
                     LogStatement::tNonrecursiveRelation(relationName, srcLocation);
             std::unique_ptr<RamStatement> newStmt =
                     std::make_unique<RamLogRelationTimer>(std::make_unique<RamSequence>(std::move(res)),
                             logTimerStatement, std::unique_ptr<RamRelationReference>(rrel->clone()));
             res.clear();
             appendStmt(res, std::move(newStmt));
         } else {
             // add table size printer
             appendStmt(res, std::make_unique<RamLogSize>(
                                     std::unique_ptr<RamRelationReference>(rrel->clone()), logSizeStatement));
         }
     }
     // done
     return std::make_unique<RamSequence>(std::move(res));
 }
translateProgram()
void souffle::AstTranslator::translateProgram (const AstTranslationUnit & translationUnit) private
translate AST to RAM Program
translates the given datalog program into an equivalent RAM program
Definition at line 1538 of file AstTranslator.cpp.
References souffle::appendStmt(), auxArityAnalysis, souffle::Global::config(), souffle::fileExtension(), souffle::AstTranslationUnit::getAnalysis(), souffle::AuxiliaryArity::getArity(), souffle::AstClause::getBodyLiterals(), souffle::getClauseNum(), souffle::AstClause::getHead(), getInputDirectives(), souffle::getName, getOutputDirectives(), souffle::AstAtom::getQualifiedName(), souffle::TypeEnvironment::getType(), souffle::getTypeQualifier(), i, makeNegationSubproofSubroutine(), makeSubproofSubroutine(), program, ramMain, ramRels, ramSubs, relation, souffle::LogStatement::runtime(), souffle::toString(), translateNonRecursiveRelation(), translateRecursiveRelation(), translateRelation(), souffle::LogStatement::tRelationLoadTime(), souffle::LogStatement::tRelationSaveTime(), typeEnv, and souffle::visitDepthFirst().
Referenced by getConstantRamRepresentation(), and translateUnit().
{
     // obtain type environment from analysis
     typeEnv = &translationUnit.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment();
     // obtain recursive clauses from analysis
     const auto* recursiveClauses = translationUnit.getAnalysis<RecursiveClauses>();
     // obtain strongly connected component (SCC) graph from analysis
     const auto& sccGraph = *translationUnit.getAnalysis<SCCGraph>();
     // obtain some topological order over the nodes of the SCC graph
     const auto& sccOrder = *translationUnit.getAnalysis<TopologicallySortedSCCGraph>();
     // obtain the schedule of relations expired at each index of the topological order
     const auto& expirySchedule = translationUnit.getAnalysis<RelationSchedule>()->schedule();
     // get auxiliary arity analysis
     auxArityAnalysis = translationUnit.getAnalysis<AuxiliaryArity>();
     // handle the case of an empty SCC graph
     if (sccGraph.getNumberOfSCCs() == 0) return;
     // a function to load relations
     const auto& makeRamLoad = [&](std::vector<std::unique_ptr<RamStatement>>& current,
                                       const AstRelation* relation, const std::string& inputDirectory,
                                       const std::string& fileExtension) {
         for (auto directives :
                 getInputDirectives(relation, Global::config().get(inputDirectory), fileExtension)) {
             std::unique_ptr<RamStatement> statement = std::make_unique<RamIO>(
                     std::unique_ptr<RamRelationReference>(translateRelation(relation)), directives);
             if (Global::config().has("profile")) {
                 const std::string logTimerStatement = LogStatement::tRelationLoadTime(
                         toString(relation->getQualifiedName()), relation->getSrcLoc());
                 statement = std::make_unique<RamLogRelationTimer>(std::move(statement), logTimerStatement,
                         std::unique_ptr<RamRelationReference>(translateRelation(relation)));
             }
             appendStmt(current, std::move(statement));
         }
     };
     // a function to store relations
     const auto& makeRamStore = [&](std::vector<std::unique_ptr<RamStatement>>& current,
                                        const AstRelation* relation, const std::string& outputDirectory,
                                        const std::string& fileExtension) {
         for (auto directives :
                 getOutputDirectives(relation, Global::config().get(outputDirectory), fileExtension)) {
             std::unique_ptr<RamStatement> statement = std::make_unique<RamIO>(
                     std::unique_ptr<RamRelationReference>(translateRelation(relation)), directives);
             if (Global::config().has("profile")) {
                 const std::string logTimerStatement = LogStatement::tRelationSaveTime(
                         toString(relation->getQualifiedName()), relation->getSrcLoc());
                 statement = std::make_unique<RamLogRelationTimer>(std::move(statement), logTimerStatement,
                         std::unique_ptr<RamRelationReference>(translateRelation(relation)));
             }
             appendStmt(current, std::move(statement));
         }
     };
     // a function to drop relations
     const auto& makeRamClear = [&](std::vector<std::unique_ptr<RamStatement>>& current,
                                        const AstRelation* relation) {
         appendStmt(current, std::make_unique<RamClear>(translateRelation(relation)));
     };
     // maintain the index of the SCC within the topological order
     size_t indexOfScc = 0;
     // create all Ram relations in ramRels
     for (const auto& scc : sccOrder.order()) {
         const auto& isRecursive = sccGraph.isRecursive(scc);
         const auto& allInterns = sccGraph.getInternalRelations(scc);
         for (const auto& rel : allInterns) {
             std::string name = rel->getQualifiedName().toString();
             auto arity = rel->getArity();
             auto auxiliaryArity = auxArityAnalysis->getArity(rel);
             auto representation = rel->getRepresentation();
             const auto& attributes = rel->getAttributes();
             std::vector<std::string> attributeNames;
             std::vector<std::string> attributeTypeQualifiers;
             for (size_t i = 0; i < rel->getArity(); ++i) {
                 attributeNames.push_back(attributes[i]->getName());
                 if (typeEnv != nullptr) {
                     attributeTypeQualifiers.push_back(
                             getTypeQualifier(typeEnv->getType(attributes[i]->getTypeName())));
                 }
             }
             ramRels[name] = std::make_unique<RamRelation>(
                     name, arity, auxiliaryArity, attributeNames, attributeTypeQualifiers, representation);
             if (isRecursive) {
                 std::string deltaName = "@delta_" + name;
                 std::string newName = "@new_" + name;
                 ramRels[deltaName] = std::make_unique<RamRelation>(deltaName, arity, auxiliaryArity,
                         attributeNames, attributeTypeQualifiers, representation);
                 ramRels[newName] = std::make_unique<RamRelation>(newName, arity, auxiliaryArity,
                         attributeNames, attributeTypeQualifiers, representation);
             }
         }
     }
     // iterate over each SCC according to the topological order
     for (const auto& scc : sccOrder.order()) {
         // make a new ram statement for the current SCC
         std::vector<std::unique_ptr<RamStatement>> current;
         // find out if the current SCC is recursive
         const auto& isRecursive = sccGraph.isRecursive(scc);
         // make variables for particular sets of relations contained within the current SCC, and,
         // predecessors and successor SCCs thereof
         const auto& allInterns = sccGraph.getInternalRelations(scc);
         const auto& internIns = sccGraph.getInternalInputRelations(scc);
         const auto& internOuts = sccGraph.getInternalOutputRelations(scc);
         // make a variable for all relations that are expired at the current SCC
         const auto& internExps = expirySchedule.at(indexOfScc).expired();
         // load all internal input relations from the facts dir with a .facts extension
         for (const auto& relation : internIns) {
             makeRamLoad(current, relation, "fact-dir", ".facts");
         }
         // compute the relations themselves
         std::unique_ptr<RamStatement> bodyStatement =
                 (!isRecursive) ? translateNonRecursiveRelation(
                                          *((const AstRelation*)*allInterns.begin()), recursiveClauses)
                                : translateRecursiveRelation(allInterns, recursiveClauses);
         appendStmt(current, std::move(bodyStatement));
         // store all internal output relations to the output dir with a .csv extension
         for (const auto& relation : internOuts) {
             makeRamStore(current, relation, "output-dir", ".csv");
         }
         // if provenance is not enabled...
         if (!Global::config().has("provenance")) {
             // otherwise, drop all  relations expired as per the topological order
             for (const auto& relation : internExps) {
                 makeRamClear(current, relation);
             }
         }
         // create subroutine for this stratum
         ramSubs["stratum_" + std::to_string(indexOfScc)] = std::make_unique<RamSequence>(std::move(current));
         indexOfScc++;
     }
     // invoke all strata
     std::vector<std::unique_ptr<RamStatement>> res;
     for (size_t i = 0; i < indexOfScc; i++) {
         appendStmt(res, std::make_unique<RamCall>("stratum_" + std::to_string(i)));
     }
     // add main timer if profiling
     if (res.size() > 0 && Global::config().has("profile")) {
         std::unique_ptr<RamStatement> newStmt = std::make_unique<RamLogTimer>(
                 std::make_unique<RamSequence>(std::move(res)), LogStatement::runtime());
         res.clear();
         appendStmt(res, std::move(newStmt));
     }
     // done for main prog
     ramMain = std::make_unique<RamSequence>(std::move(res));
     // add subroutines for each clause
     if (Global::config().has("provenance")) {
         visitDepthFirst(*program, [&](const AstClause& clause) {
             std::stringstream relName;
             relName << clause.getHead()->getQualifiedName();
             // do not add subroutines for info relations or facts
             if (relName.str().find("@info") != std::string::npos || clause.getBodyLiterals().empty()) {
                 return;
             }
             std::string subroutineLabel =
                     relName.str() + "_" + std::to_string(getClauseNum(program, &clause)) + "_subproof";
             ramSubs[subroutineLabel] = makeSubproofSubroutine(clause);
             std::string negationSubroutineLabel = relName.str() + "_" +
                                                   std::to_string(getClauseNum(program, &clause)) +
                                                   "_negation_subproof";
             ramSubs[negationSubroutineLabel] = makeNegationSubproofSubroutine(clause);
         });
     }
 }
translateRecursiveRelation()
std::unique_ptr< RamStatement > souffle::AstTranslator::translateRecursiveRelation (const std::set< const AstRelation *> & scc, const RecursiveClauses * recursiveClauses) private
translate RAM code for recursive relations in a strongly-connected component
generate RAM code for recursive relations in a strongly-connected component
Definition at line 1082 of file AstTranslator.cpp.
References souffle::appendStmt(), souffle::AstAtom::clone(), souffle::RamRelationReference::clone(), souffle::Global::config(), souffle::LogStatement::cRecursiveRelation(), souffle::EQREL, souffle::fatal(), souffle::RamRelationReference::get(), souffle::RamRelation::getArity(), souffle::getAtomRelation(), souffle::getClauses(), souffle::getName, souffle::RamRelation::getRepresentation(), i, j, k, nameUnnamedVariables(), souffle::LogStatement::nRecursiveRelation(), souffle::LogStatement::nRecursiveRule(), program, souffle::RecursiveClauses::recursive(), rule, souffle::AstAtom::setQualifiedName(), souffle::stringify(), souffle::toString(), souffle::AstTranslator::ClauseTranslator::translateClause(), translateDeltaRelation(), translateNewRelation(), translateNonRecursiveRelation(), translateRelation(), souffle::LogStatement::tRecursiveRelation(), and souffle::LogStatement::tRecursiveRule().
Referenced by getConstantRamRepresentation(), and translateProgram().
{
     // initialize sections
     std::vector<std::unique_ptr<RamStatement>> preamble;
     std::vector<std::unique_ptr<RamStatement>> updateTable;
     std::vector<std::unique_ptr<RamStatement>> postamble;
     auto genMerge = [](const RamRelationReference* dest,
                             const RamRelationReference* src) -> std::unique_ptr<RamStatement> {
         std::vector<std::unique_ptr<RamExpression>> values;
         if (src->get()->getArity() == 0) {
             return std::make_unique<RamQuery>(std::make_unique<RamFilter>(
                     std::make_unique<RamNegation>(std::make_unique<RamEmptinessCheck>(
                             std::unique_ptr<RamRelationReference>(src->clone()))),
                     std::make_unique<RamProject>(
                             std::unique_ptr<RamRelationReference>(dest->clone()), std::move(values))));
         }
         for (std::size_t i = 0; i < dest->get()->getArity(); i++) {
             values.push_back(std::make_unique<RamTupleElement>(0, i));
         }
         std::unique_ptr<RamStatement> stmt = std::make_unique<RamQuery>(
                 std::make_unique<RamScan>(std::unique_ptr<RamRelationReference>(src->clone()), 0,
                         std::make_unique<RamProject>(
                                 std::unique_ptr<RamRelationReference>(dest->clone()), std::move(values))));
         if (dest->get()->getRepresentation() == RelationRepresentation::EQREL) {
             stmt = std::make_unique<RamSequence>(
                     std::make_unique<RamExtend>(std::unique_ptr<RamRelationReference>(dest->clone()),
                             std::unique_ptr<RamRelationReference>(src->clone())),
                     std::move(stmt));
         }
         return stmt;
     };
     // --- create preamble ---
     /* Compute non-recursive clauses for relations in scc and push
        the results in their delta tables. */
     for (const AstRelation* rel : scc) {
         /* create update statements for fixpoint (even iteration) */
         std::unique_ptr<RamStatement> updateRelTable = std::make_unique<RamSequence>(
                 genMerge(translateRelation(rel).get(), translateNewRelation(rel).get()),
                 std::make_unique<RamSwap>(translateDeltaRelation(rel), translateNewRelation(rel)),
                 std::make_unique<RamClear>(translateNewRelation(rel)));
         /* measure update time for each relation */
         if (Global::config().has("profile")) {
             updateRelTable = std::make_unique<RamLogRelationTimer>(std::move(updateRelTable),
                     LogStatement::cRecursiveRelation(toString(rel->getQualifiedName()), rel->getSrcLoc()),
                     translateNewRelation(rel));
         }
         /* drop temporary tables after recursion */
         appendStmt(postamble, std::make_unique<RamClear>(translateDeltaRelation(rel)));
         appendStmt(postamble, std::make_unique<RamClear>(translateNewRelation(rel)));
         /* Generate code for non-recursive part of relation */
         /* Generate merge operation for temp tables */
         appendStmt(preamble, translateNonRecursiveRelation(*rel, recursiveClauses));
         appendStmt(preamble, genMerge(translateDeltaRelation(rel).get(), translateRelation(rel).get()));
         /* Add update operations of relations to parallel statements */
         appendStmt(updateTable, std::move(updateRelTable));
     }
     // --- build main loop ---
     std::vector<std::unique_ptr<RamStatement>> loopSeq;
     // create a utility to check SCC membership
     auto isInSameSCC = [&](const AstRelation* rel) {
         return std::find(scc.begin(), scc.end(), rel) != scc.end();
     };
     /* Compute temp for the current tables */
     for (const AstRelation* rel : scc) {
         std::vector<std::unique_ptr<RamStatement>> loopRelSeq;
         /* Find clauses for relation rel */
         for (const auto& cl : getClauses(*program, *rel)) {
             // skip non-recursive clauses
             if (!recursiveClauses->recursive(cl)) {
                 continue;
             }
             // each recursive rule results in several operations
             int version = 0;
             const auto& atoms = getBodyLiterals<AstAtom>(*cl);
             for (size_t j = 0; j < atoms.size(); ++j) {
                 const AstAtom* atom = atoms[j];
                 const AstRelation* atomRelation = getAtomRelation(atom, program);
                 // only interested in atoms within the same SCC
                 if (!isInSameSCC(atomRelation)) {
                     continue;
                 }
                 // modify the processed rule to use delta relation and write to new relation
                 std::unique_ptr<AstClause> r1(cl->clone());
                 r1->getHead()->setQualifiedName(translateNewRelation(rel)->get()->getName());
                 getBodyLiterals<AstAtom>(*r1)[j]->setQualifiedName(
                         translateDeltaRelation(atomRelation)->get()->getName());
                 if (Global::config().has("provenance")) {
                     r1->addToBody(std::make_unique<AstProvenanceNegation>(
                             std::unique_ptr<AstAtom>(cl->getHead()->clone())));
                 } else {
                     if (r1->getHead()->getArity() > 0) {
                         r1->addToBody(std::make_unique<AstNegation>(
                                 std::unique_ptr<AstAtom>(cl->getHead()->clone())));
                     }
                 }
                 // replace wildcards with variables (reduces indices when wildcards are used in recursive
                 // atoms)
                 nameUnnamedVariables(r1.get());
                 // reduce R to P ...
                 for (size_t k = j + 1; k < atoms.size(); k++) {
                     if (isInSameSCC(getAtomRelation(atoms[k], program))) {
                         AstAtom* cur = getBodyLiterals<AstAtom>(*r1)[k]->clone();
                         cur->setQualifiedName(
                                 translateDeltaRelation(getAtomRelation(atoms[k], program))->get()->getName());
                         r1->addToBody(std::make_unique<AstNegation>(std::unique_ptr<AstAtom>(cur)));
                     }
                 }
                 std::unique_ptr<RamStatement> rule =
                         ClauseTranslator(*this).translateClause(*r1, *cl, version);
                 /* add logging */
                 if (Global::config().has("profile")) {
                     const std::string& relationName = toString(rel->getQualifiedName());
                     const SrcLocation& srcLocation = cl->getSrcLoc();
                     const std::string clauseText = stringify(toString(*cl));
                     const std::string logTimerStatement =
                             LogStatement::tRecursiveRule(relationName, version, srcLocation, clauseText);
                     const std::string logSizeStatement =
                             LogStatement::nRecursiveRule(relationName, version, srcLocation, clauseText);
                     rule = std::make_unique<RamLogRelationTimer>(
                             std::move(rule), logTimerStatement, translateNewRelation(rel));
                 }
                 // add debug info
                 std::ostringstream ds;
                 ds << toString(*cl) << "\nin file ";
                 ds << cl->getSrcLoc();
                 rule = std::make_unique<RamDebugInfo>(std::move(rule), ds.str());
                 // add to loop body
                 appendStmt(loopRelSeq, std::move(rule));
                 // increment version counter
                 version++;
             }
             if (cl->getExecutionPlan() != nullptr) {
                 // ensure that all required versions have been created, as expected
                 int maxVersion = -1;
                 for (auto const& cur : cl->getExecutionPlan()->getOrders()) {
                     maxVersion = std::max(cur.first, maxVersion);
                 }
                 assert(version > maxVersion && "missing clause versions");
             }
         }
         // if there was no rule, continue
         if (loopRelSeq.size() == 0) {
             continue;
         }
         // label all versions
         if (Global::config().has("profile")) {
             const std::string& relationName = toString(rel->getQualifiedName());
             const SrcLocation& srcLocation = rel->getSrcLoc();
             const std::string logTimerStatement = LogStatement::tRecursiveRelation(relationName, srcLocation);
             const std::string logSizeStatement = LogStatement::nRecursiveRelation(relationName, srcLocation);
             std::unique_ptr<RamStatement> newStmt = std::make_unique<RamLogRelationTimer>(
                     std::make_unique<RamSequence>(std::move(loopRelSeq)), logTimerStatement,
                     translateNewRelation(rel));
             loopRelSeq.clear();
             appendStmt(loopRelSeq, std::move(newStmt));
         }
         /* add rule computations of a relation to parallel statement */
         appendStmt(loopSeq, std::make_unique<RamSequence>(std::move(loopRelSeq)));
     }
     std::unique_ptr<RamParallel> loop = std::make_unique<RamParallel>(std::move(loopSeq));
     /* construct exit conditions for odd and even iteration */
     auto addCondition = [](std::unique_ptr<RamCondition>& cond, std::unique_ptr<RamCondition> clause) {
         cond = ((cond) ? std::make_unique<RamConjunction>(std::move(cond), std::move(clause))
                        : std::move(clause));
     };
     std::unique_ptr<RamCondition> exitCond;
     for (const AstRelation* rel : scc) {
         addCondition(exitCond, std::make_unique<RamEmptinessCheck>(translateNewRelation(rel)));
     }
     /* construct fixpoint loop  */
     std::vector<std::unique_ptr<RamStatement>> res;
     if (preamble.size() > 0) {
         appendStmt(res, std::make_unique<RamSequence>(std::move(preamble)));
     }
     if (!loop->getStatements().empty() && exitCond && updateTable.size() > 0) {
         appendStmt(res, std::make_unique<RamLoop>(std::make_unique<RamSequence>(std::move(loop),
                                 std::make_unique<RamExit>(std::move(exitCond)),
                                 std::make_unique<RamSequence>(std::move(updateTable)))));
     }
     if (postamble.size() > 0) {
         appendStmt(res, std::make_unique<RamSequence>(std::move(postamble)));
     }
     if (res.size() > 0) {
         return std::make_unique<RamSequence>(std::move(res));
     }
     fatal("Not Implemented");
 }
translateRelation() [1/2]
std::unique_ptr< RamRelationReference > souffle::AstTranslator::translateRelation (const AstAtom * atom) private
a utility to translate atoms to relations
Definition at line 269 of file AstTranslator.cpp.
References createRelationReference(), souffle::AstAtom::getQualifiedName(), and getRelationName().
Referenced by getRelationName(), makeNegationSubproofSubroutine(), translateConstraint(), translateDeltaRelation(), translateNewRelation(), translateNonRecursiveRelation(), translateProgram(), and translateRecursiveRelation().
{
     return createRelationReference(getRelationName(atom->getQualifiedName()));
 }
translateRelation() [2/2]
std::unique_ptr< RamRelationReference > souffle::AstTranslator::translateRelation (const AstRelation * rel, const std::string relationNamePrefix = "") private
translate an AST relation to a RAM relation
Definition at line 273 of file AstTranslator.cpp.
References createRelationReference(), souffle::AstRelation::getQualifiedName(), and getRelationName().
{
     return createRelationReference(relationNamePrefix + getRelationName(rel->getQualifiedName()));
 }
translateUnit()
std::unique_ptr< RamTranslationUnit > souffle::AstTranslator::translateUnit (AstTranslationUnit & tu)
translates AST to translation unit
Definition at line 1752 of file AstTranslator.cpp.
References souffle::DebugReport::addSection(), souffle::Global::config(), souffle::test::count(), souffle::AstTranslationUnit::getDebugReport(), souffle::AstTranslationUnit::getErrorReport(), souffle::AstTranslationUnit::getProgram(), getSymbolTable(), souffle::test::now(), program, ramMain, ramRels, ramSubs, and translateProgram().
Referenced by souffle::main().
{
     auto ram_start = std::chrono::high_resolution_clock::now();
     program = tu.getProgram();
     translateProgram(tu);
     SymbolTable& symTab = getSymbolTable();
     ErrorReport& errReport = tu.getErrorReport();
     DebugReport& debugReport = tu.getDebugReport();
     std::vector<std::unique_ptr<RamRelation>> rels;
     for (auto& cur : ramRels) {
         rels.push_back(std::move(cur.second));
     }
     if (nullptr == ramMain) {
         ramMain = std::make_unique<RamSequence>();
     }
     std::unique_ptr<RamProgram> ramProg =
             std::make_unique<RamProgram>(std::move(rels), std::move(ramMain), std::move(ramSubs));
     if (!Global::config().get("debug-report").empty()) {
         if (ramProg) {
             auto ram_end = std::chrono::high_resolution_clock::now();
             std::string runtimeStr =
                     "(" + std::to_string(std::chrono::duration<double>(ram_end - ram_start).count()) + "s)";
             std::stringstream ramProgStr;
             ramProgStr << *ramProg;
             debugReport.addSection("ram-program", "RAM Program " + runtimeStr, ramProgStr.str());
         }
     }
     return std::make_unique<RamTranslationUnit>(
             std::move(ramProg), std::move(symTab), errReport, debugReport);
 }
translateValue()
std::unique_ptr< RamExpression > souffle::AstTranslator::translateValue (const AstArgument * arg, const ValueIndex & index) private
translate an AST argument to a RAM value
Definition at line 286 of file AstTranslator.cpp.
References souffle::fatal(), souffle::AstNumericConstant::Float, souffle::AstUserDefinedFunctor::getArgsTypes(), souffle::AstTerm::getArguments(), souffle::AstConstant::getConstant(), souffle::AstTranslator::ValueIndex::getDefinitionPoint(), souffle::AstIntrinsicFunctor::getFunctionInfo(), souffle::AstTranslator::ValueIndex::getGeneratorLoc(), souffle::AstUserDefinedFunctor::getName(), souffle::AstSubroutineArgument::getNumber(), souffle::AstUserDefinedFunctor::getReturnType(), getSymbolTable(), souffle::AstNumericConstant::getType(), souffle::AstNumericConstant::Int, souffle::AstTranslator::ValueIndex::isDefined(), souffle::SymbolTable::lookup(), makeRamTupleElement(), souffle::RamFloatFromString(), souffle::RamSignedFromString(), souffle::RamUnsignedFromString(), translateValue(), and souffle::AstNumericConstant::Uint.
Referenced by getRelationName(), makeNegationSubproofSubroutine(), translateConstraint(), and translateValue().
{
     if (arg == nullptr) {
         return nullptr;
     }
     class ValueTranslator : public AstVisitor<std::unique_ptr<RamExpression>> {
         AstTranslator& translator;
         const ValueIndex& index;
     public:
         ValueTranslator(AstTranslator& translator, const ValueIndex& index)
                 : translator(translator), index(index) {}
         std::unique_ptr<RamExpression> visitVariable(const AstVariable& var) override {
             assert(index.isDefined(var) && "variable not grounded");
             return makeRamTupleElement(index.getDefinitionPoint(var));
         }
         std::unique_ptr<RamExpression> visitUnnamedVariable(const AstUnnamedVariable&) override {
             return std::make_unique<RamUndefValue>();
         }
         std::unique_ptr<RamExpression> visitNumericConstant(const AstNumericConstant& c) override {
             assert(c.getType().has_value() && "At this points all constants should have type.");
             switch (*c.getType()) {
                 case AstNumericConstant::Type::Int:
                     return std::make_unique<RamSignedConstant>(
                             RamSignedFromString(c.getConstant(), nullptr, 0));
                 case AstNumericConstant::Type::Uint:
                     return std::make_unique<RamUnsignedConstant>(
                             RamUnsignedFromString(c.getConstant(), nullptr, 0));
                 case AstNumericConstant::Type::Float:
                     return std::make_unique<RamFloatConstant>(RamFloatFromString(c.getConstant()));
             }
             fatal("unexpected numeric constant type");
         }
         std::unique_ptr<RamExpression> visitStringConstant(const AstStringConstant& c) override {
             return std::make_unique<RamSignedConstant>(translator.getSymbolTable().lookup(c.getConstant()));
         }
         std::unique_ptr<RamExpression> visitNilConstant(const AstNilConstant&) override {
             return std::make_unique<RamSignedConstant>(0);
         }
         std::unique_ptr<RamExpression> visitIntrinsicFunctor(const AstIntrinsicFunctor& inf) override {
             std::vector<std::unique_ptr<RamExpression>> values;
             for (const auto& cur : inf.getArguments()) {
                 values.push_back(translator.translateValue(cur, index));
             }
             auto* info = inf.getFunctionInfo();
             assert(info && "no overload picked for instrinsic; missing transform pass?");
             if (info->multipleResults) {
                 return translator.makeRamTupleElement(index.getGeneratorLoc(inf));
             } else {
                 return std::make_unique<RamIntrinsicOperator>(info->op, std::move(values));
             }
         }
         std::unique_ptr<RamExpression> visitUserDefinedFunctor(const AstUserDefinedFunctor& udf) override {
             // Sanity check.
             assert(udf.getArguments().size() == udf.getArgsTypes().size());
             std::vector<std::unique_ptr<RamExpression>> values;
             for (const auto& cur : udf.getArguments()) {
                 values.push_back(translator.translateValue(cur, index));
             }
             return std::make_unique<RamUserDefinedOperator>(
                     udf.getName(), udf.getArgsTypes(), udf.getReturnType(), std::move(values));
         }
         std::unique_ptr<RamExpression> visitCounter(const AstCounter&) override {
             return std::make_unique<RamAutoIncrement>();
         }
         std::unique_ptr<RamExpression> visitRecordInit(const AstRecordInit& init) override {
             std::vector<std::unique_ptr<RamExpression>> values;
             for (const auto& cur : init.getArguments()) {
                 values.push_back(translator.translateValue(cur, index));
             }
             return std::make_unique<RamPackRecord>(std::move(values));
         }
         std::unique_ptr<RamExpression> visitAggregator(const AstAggregator& agg) override {
             // here we look up the location the aggregation result gets bound
             return translator.makeRamTupleElement(index.getGeneratorLoc(agg));
         }
         std::unique_ptr<RamExpression> visitSubroutineArgument(const AstSubroutineArgument& subArg) override {
             return std::make_unique<RamSubroutineArgument>(subArg.getNumber());
         }
     };
     return ValueTranslator(*this, index)(*arg);
 }
Field Documentation
auxArityAnalysis
const AuxiliaryArity* souffle::AstTranslator::auxArityAnalysis = nullptr private
Auxiliary Arity Analysis.
Definition at line 95 of file AstTranslator.h.
Referenced by getEvaluationArity(), getOutputDirectives(), makeNegationSubproofSubroutine(), makeSubproofSubroutine(), translateDirectives(), and translateProgram().
program
const AstProgram* souffle::AstTranslator::program = nullptr private
AST program.
Definition at line 74 of file AstTranslator.h.
Referenced by getEvaluationArity(), getInputDirectives(), getOutputDirectives(), getRecordsTypes(), translateNonRecursiveRelation(), translateProgram(), translateRecursiveRelation(), and translateUnit().
ramMain
std::unique_ptr<RamStatement> souffle::AstTranslator::ramMain private
RAM program.
Definition at line 80 of file AstTranslator.h.
Referenced by translateProgram(), and translateUnit().
RamRecordTypes
Json souffle::AstTranslator::RamRecordTypes private
Record types information - used in Ram for I/O.
Definition at line 89 of file AstTranslator.h.
Referenced by getRecordsTypes().
ramRels
std::map<std::string, std::unique_ptr<RamRelation> > souffle::AstTranslator::ramRels private
RAM relations.
Definition at line 86 of file AstTranslator.h.
Referenced by createRelationReference(), translateProgram(), and translateUnit().
ramSubs
std::map<std::string, std::unique_ptr<RamStatement> > souffle::AstTranslator::ramSubs private
Subroutines.
Definition at line 83 of file AstTranslator.h.
Referenced by translateProgram(), and translateUnit().
symbolTable
SymbolTable souffle::AstTranslator::symbolTable private
Symbol Table.
Definition at line 92 of file AstTranslator.h.
Referenced by getSymbolTable().
typeEnv
const TypeEnvironment* souffle::AstTranslator::typeEnv = nullptr private
Type environment.
Definition at line 77 of file AstTranslator.h.
Referenced by getRecordsTypes(), translateDirectives(), and translateProgram().
The documentation for this class was generated from the following files:
AstTranslator.h
AstTranslator.cpp