souffle: souffle::AstSemanticCheckerImpl Struct Reference
souffle::AstSemanticCheckerImpl Struct Reference
Public Member Functions
AstSemanticCheckerImpl (AstTranslationUnit &tu)
Data Fields
AstTranslationUnit & tu
Private Member Functions
void checkAggregator (const AstAggregator &aggregator)
void checkArgument (const AstArgument &arg)
void checkAtom (const AstAtom &atom)
void checkClause (const AstClause &clause)
void checkComplexRule (std::set< const AstClause *> multiRule)
void checkConstant (const AstArgument &argument)
void checkFact (const AstClause &fact)
void checkInlining ()
void checkIO ()
void checkLiteral (const AstLiteral &literal)
void checkNamespaces ()
void checkRecordType (const AstRecordType &type)
void checkRelation (const AstRelation &relation)
void checkRelationDeclaration (const AstRelation &relation)
void checkSubsetType (const AstSubsetType &type)
void checkType (const AstType &type)
void checkUnionType (const AstUnionType &type)
void checkWitnessProblem ()
bool isDependent (const AstClause &agg1, const AstClause &agg2)
agg1, agg2 are clauses which contain no head, and consist of a single literal that contains an aggregate.
Private Attributes
const IOType & ioTypes = *tu.getAnalysis<IOType>()
const PrecedenceGraph & precedenceGraph = *tu.getAnalysis<PrecedenceGraph>()
const AstProgram & program = *tu.getProgram()
const RecursiveClauses & recursiveClauses = *tu.getAnalysis<RecursiveClauses>()
ErrorReport & report = tu.getErrorReport()
const SCCGraph & sccGraph = *tu.getAnalysis<SCCGraph>()
const TypeAnalysis & typeAnalysis = *tu.getAnalysis<TypeAnalysis>()
const TypeEnvironment & typeEnv = typeEnvAnalysis.getTypeEnvironment()
const TypeEnvironmentAnalysis & typeEnvAnalysis = *tu.getAnalysis<TypeEnvironmentAnalysis>()
Detailed Description
Definition at line 68 of file AstSemanticChecker.cpp.
Constructor & Destructor Documentation
AstSemanticCheckerImpl()
souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl (AstTranslationUnit & tu)
Definition at line 112 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addDiagnostic(), souffle::ErrorReport::addError(), souffle::all_of(), souffle::any_of(), souffle::AstQualifiedName::append(), souffle::TypeSet::begin(), checkClause(), checkComplexRule(), checkInlining(), checkIO(), checkNamespaces(), checkRelation(), checkType(), checkWitnessProblem(), souffle::Global::config(), souffle::TypeSet::empty(), souffle::Diagnostic::ERROR, souffle::fatal(), souffle::Float, souffle::AstNumericConstant::Float, tinyformat::format(), souffle::AstUserDefinedFunctor::getArgType(), souffle::AstAtom::getArguments(), souffle::AstTerm::getArguments(), souffle::getAtomRelation(), souffle::getBinaryConstraintTypes(), souffle::getClauses(), souffle::AstProgram::getClauses(), souffle::AstIntrinsicFunctor::getFunction(), souffle::AstIntrinsicFunctor::getFunctionInfo(), souffle::SCCGraph::getInternalRelations(), souffle::AstBinaryConstraint::getLHS(), souffle::AstVariable::getName(), souffle::AstBinaryConstraint::getOperator(), souffle::AstAggregator::getOperator(), souffle::AstRelation::getQualifiedName(), souffle::getRelation(), souffle::AstProgram::getRelations(), souffle::AstUserDefinedFunctor::getReturnType(), souffle::AstBinaryConstraint::getRHS(), souffle::SCCGraph::getSCC(), souffle::AstNode::getSrcLoc(), souffle::AstNumericConstant::getType(), souffle::TypeEnvironment::getType(), souffle::AstTypeCast::getType(), souffle::getTypeAttributeAggregate(), souffle::TypeAnalysis::getTypes(), souffle::AstProgram::getTypes(), souffle::AstTypeCast::getValue(), souffle::hasClauseWithAggregatedRelation(), souffle::hasClauseWithNegatedRelation(), souffle::haveCommonSupertype(), i, souffle::AstNumericConstant::Int, souffle::isOfKind(), souffle::isOrderedBinaryConstraintOp(), souffle::SCCGraph::isRecursive(), souffle::isSubtypeOf(), souffle::TypeEnvironment::isType(), souffle::isValidFunctorOpArity(), souffle::join(), souffle::Record, relation, souffle::Signed, souffle::TypeSet::size(), souffle::splitString(), souffle::profile::ss, souffle::SUPPRESSED, souffle::Symbol, souffle::toString(), types, souffle::AstNumericConstant::Uint, souffle::Unsigned, souffle::validOverloads(), souffle::GroundedTermsChecker::verify(), and souffle::visitDepthFirst().
                                                                      : tu(tu) {
     // suppress warnings for given relations
     if (Global::config().has("suppress-warnings")) {
         std::vector<std::string> suppressedRelations =
                 splitString(Global::config().get("suppress-warnings"), ',');
         if (std::find(suppressedRelations.begin(), suppressedRelations.end(), "*") !=
                 suppressedRelations.end()) {
             // mute all relations
             for (AstRelation* rel : program.getRelations()) {
                 rel->addQualifier(RelationQualifier::SUPPRESSED);
             }
         } else {
             // mute only the given relations (if they exist)
             for (auto& relname : suppressedRelations) {
                 const std::vector<std::string> comps = splitString(relname, '.');
                 if (!comps.empty()) {
                     // generate the relation identifier
                     AstQualifiedName relid(comps[0]);
                     for (size_t i = 1; i < comps.size(); i++) {
                         relid.append(comps[i]);
                     }
                     // update suppressed qualifier if the relation is found
                     if (AstRelation* rel = getRelation(program, relid)) {
                         rel->addQualifier(RelationQualifier::SUPPRESSED);
                     }
                 }
             }
         }
     }
     // Check types in AST.
     for (const auto* astType : program.getTypes()) {
         checkType(*astType);
     }
     // check rules
     for (auto* rel : program.getRelations()) {
         checkRelation(*rel);
     }
     for (auto* clause : program.getClauses()) {
         checkClause(*clause);
     }
     // Group clauses that stem from a single complex rule
     // with multiple headers/disjunction etc. The grouping
     // is performed via their source-location.
     std::map<SrcLocation, std::set<const AstClause*>> multiRuleMap;
     for (auto* clause : program.getClauses()) {
         // collect clauses of a multi rule, i.e., they have the same source locator
         multiRuleMap[clause->getSrcLoc()].insert(clause);
     }
     // check complex rule
     for (const auto& multiRule : multiRuleMap) {
         checkComplexRule(multiRule.second);
     }
     checkNamespaces();
     checkIO();
     checkWitnessProblem();
     checkInlining();
     // Run grounded terms checker
     GroundedTermsChecker().verify(tu);
     // get the list of components to be checked (clauses w/ relation decls)
     std::vector<const AstNode*> nodes;
     for (const auto& rel : program.getRelations()) {
         for (const auto& cls : getClauses(program, *rel)) {
             nodes.push_back(cls);
         }
     }
     // -- type checks --
     // check if in all atoms the arguments are subtypes of declared types.
     visitDepthFirst(nodes, [&](const AstAtom& atom) {
         auto relation = getAtomRelation(&atom, &program);
         if (relation == nullptr) {
             return;  // error unrelated to types.
         }
         auto attributes = relation->getAttributes();
         auto arguments = atom.getArguments();
         if (attributes.size() != arguments.size()) {
             return;  // error in input program
         }
         for (size_t i = 0; i < attributes.size(); ++i) {
             auto& typeName = attributes[i]->getTypeName();
             if (typeEnv.isType(typeName)) {
                 auto argTypes = typeAnalysis.getTypes(arguments[i]);
                 auto& attributeType = typeEnv.getType(typeName);
                 if (argTypes.isAll() || argTypes.empty()) {
                     continue;  // This will be reported later.
                 }
                 // Attribute and argument type agree if, argument type is a subtype of declared type
                 // or is of the appropriate constant type or the (constant) record type.
                 bool validAttribute = all_of(argTypes, [&attributeType](const Type& type) {
                     if (isSubtypeOf(type, attributeType)) return true;
                     if (!isSubtypeOf(attributeType, type)) return false;
                     if (isA<ConstantType>(type)) return true;
                     return isA<RecordType>(type) && !isA<SubsetType>(type);
                 });
                 if (!validAttribute) {
                     if (!Global::config().has("legacy")) {
                         report.addError("Atoms argument type is not a subtype of its declared type",
                                 arguments[i]->getSrcLoc());
                     }
                 }
             }
         }
     });
     // - variables -
     visitDepthFirst(nodes, [&](const AstVariable& var) {
         if (typeAnalysis.getTypes(&var).empty()) {
             report.addError("Unable to deduce type for variable " + var.getName(), var.getSrcLoc());
         }
     });
     // - constants -
     // all string constants are used as symbols
     visitDepthFirst(nodes, [&](const AstStringConstant& constant) {
         TypeSet types = typeAnalysis.getTypes(&constant);
         if (!isOfKind(types, TypeAttribute::Symbol)) {
             report.addError("Symbol constant (type mismatch)", constant.getSrcLoc());
         }
     });
     // TODO (darth_tytus): Improve error messages.
     // At this stage each constant should have a type (assigned by a transformer)
     visitDepthFirst(nodes, [&](const AstNumericConstant& constant) {
         TypeSet types = typeAnalysis.getTypes(&constant);
         // No type could be assigned.
         if (!constant.getType().has_value()) {
             report.addError("Ambiguous constant (unable to deduce type)", constant.getSrcLoc());
             return;
         }
         switch (*constant.getType()) {
             case AstNumericConstant::Type::Int:
                 if (!isOfKind(types, TypeAttribute::Signed)) {
                     report.addError("Number constant (type mismatch)", constant.getSrcLoc());
                 }
                 break;
             case AstNumericConstant::Type::Uint:
                 if (!isOfKind(types, TypeAttribute::Unsigned)) {
                     report.addError("Unsigned constant (type mismatch)", constant.getSrcLoc());
                 }
                 break;
             case AstNumericConstant::Type::Float:
                 if (!isOfKind(types, TypeAttribute::Float)) {
                     report.addError("Float constant (type mismatch)", constant.getSrcLoc());
                 }
                 break;
         }
     });
     // all nil constants are used as records
     visitDepthFirst(nodes, [&](const AstNilConstant& constant) {
         TypeSet types = typeAnalysis.getTypes(&constant);
         if (!isOfKind(types, TypeAttribute::Record)) {
             report.addError("Nil constant used as a non-record", constant.getSrcLoc());
             return;
         }
     });
     // record initializations have the same size as their types
     visitDepthFirst(nodes, [&](const AstRecordInit& constant) {
         TypeSet types = typeAnalysis.getTypes(&constant);
         if (!isOfKind(types, TypeAttribute::Record) || types.size() != 1) {
             report.addError("Ambiguous record", constant.getSrcLoc());
             return;
         }
         // At this point we know that there is exactly one type in set, so we can take it.
         auto& recordType = *as<RecordType>(*types.begin());
         if (recordType.getFields().size() != constant.getArguments().size()) {
             report.addError("Wrong number of arguments given to record", constant.getSrcLoc());
             return;
         }
     });
     // type casts name a valid type
     visitDepthFirst(nodes, [&](const AstTypeCast& cast) {
         if (!typeEnv.isType(cast.getType())) {
             report.addError(
                     tfm::format("Type cast to the undeclared type \"%s\"", cast.getType()), cast.getSrcLoc());
             return;
         }
         auto& castTypes = typeAnalysis.getTypes(&cast);
         auto& argTypes = typeAnalysis.getTypes(cast.getValue());
         if (castTypes.isAll() || castTypes.size() != 1) {
             report.addError("Unable to deduce type of the argument (cast)", cast.getSrcLoc());
             return;
         }
         // This should be reported elsewhere
         if (argTypes.isAll() || castTypes.size() != 1) {
             return;
         }
         // We know that both sets have size 1.
         auto& castTy = *castTypes.begin();
         auto& argTy = *argTypes.begin();
         if (!haveCommonSupertype(castTy, argTy)) {
             report.addError(
                     tfm::format(R"(Type "%s" can't be converted to "%s")", argTy, castTy), cast.getSrcLoc());
             return;
         }
     });
     // - functors -
     visitDepthFirst(nodes, [&](const AstIntrinsicFunctor& fun) {
         if (!fun.getFunctionInfo()) {  // no info => no overload found during inference
             auto args = fun.getArguments();
             if (!isValidFunctorOpArity(fun.getFunction(), args.size())) {
                 report.addError("invalid overload (arity mismatch)", fun.getSrcLoc());
                 return;
             }
             assert(validOverloads(typeAnalysis, fun).empty() && "polymorphic transformation wasn't applied?");
             report.addError("no valid overloads", fun.getSrcLoc());
         }
     });
     visitDepthFirst(nodes, [&](const AstUserDefinedFunctor& fun) {
         // check type of result
         const TypeSet& resultType = typeAnalysis.getTypes(&fun);
         if (!isOfKind(resultType, fun.getReturnType())) {
             switch (fun.getReturnType()) {
                 case TypeAttribute::Signed:
                     report.addError("Non-numeric use for numeric functor", fun.getSrcLoc());
                     break;
                 case TypeAttribute::Unsigned:
                     report.addError("Non-unsigned use for unsigned functor", fun.getSrcLoc());
                     break;
                 case TypeAttribute::Float:
                     report.addError("Non-float use for float functor", fun.getSrcLoc());
                     break;
                 case TypeAttribute::Symbol:
                     report.addError("Non-symbolic use for symbolic functor", fun.getSrcLoc());
                     break;
                 case TypeAttribute::Record: fatal("Invalid return type");
             }
         }
         size_t i = 0;
         for (auto arg : fun.getArguments()) {
             if (!isOfKind(typeAnalysis.getTypes(arg), fun.getArgType(i))) {
                 switch (fun.getArgType(i)) {
                     case TypeAttribute::Signed:
                         report.addError("Non-numeric argument for functor", arg->getSrcLoc());
                         break;
                     case TypeAttribute::Symbol:
                         report.addError("Non-symbolic argument for functor", arg->getSrcLoc());
                         break;
                     case TypeAttribute::Unsigned:
                         report.addError("Non-unsigned argument for functor", arg->getSrcLoc());
                         break;
                     case TypeAttribute::Float:
                         report.addError("Non-float argument for functor", arg->getSrcLoc());
                         break;
                     case TypeAttribute::Record: fatal("Invalid argument type");
                 }
             }
             ++i;
         }
     });
     // - binary relation -
     visitDepthFirst(nodes, [&](const AstBinaryConstraint& constraint) {
         auto op = constraint.getOperator();
         auto left = constraint.getLHS();
         auto right = constraint.getRHS();
         auto opRamTypes = getBinaryConstraintTypes(op);
         // Skip checks if either side is `Bottom` b/c it just adds noise.
         // The unable-to-deduce-type checker will point out the issue.
         if (typeAnalysis.getTypes(left).empty() || typeAnalysis.getTypes(right).empty()) return;
         // give them a slightly nicer error
         if (isOrderedBinaryConstraintOp(op) && typeAnalysis.getTypes(left) != typeAnalysis.getTypes(right)) {
             report.addError("Cannot compare different types", constraint.getSrcLoc());
         } else {
             auto checkTyAttr = [&](AstArgument const& side) {
                 auto opMatchesType = any_of(opRamTypes,
                         [&](auto& ramType) { return isOfKind(typeAnalysis.getTypes(&side), ramType); });
                 if (!opMatchesType) {
                     std::stringstream ss;
                     ss << "Constraint requires an operand of type "
                        << join(opRamTypes, " or ", [&](auto& out, auto& ramTy) {
                               switch (ramTy) {
                                   case TypeAttribute::Signed: out << "`number`"; break;
                                   case TypeAttribute::Symbol: out << "`symbol`"; break;
                                   case TypeAttribute::Unsigned: out << "`unsigned`"; break;
                                   case TypeAttribute::Float: out << "`float`"; break;
                                   case TypeAttribute::Record: out << "a record"; break;
                               }
                           });
                     report.addError(ss.str(), side.getSrcLoc());
                 }
             };
             checkTyAttr(*left);
             checkTyAttr(*right);
         }
     });
     visitDepthFirst(nodes, [&](const AstAggregator& aggregator) {
         auto op = aggregator.getOperator();
         auto aggregatorType = typeAnalysis.getTypes(&aggregator);
         TypeAttribute opType = getTypeAttributeAggregate(op);
         // Check if operation type and return type agree.
         if (!isOfKind(aggregatorType, opType)) {
             report.addError("Couldn't assign types to the aggregator", aggregator.getSrcLoc());
         }
     });
     // - stratification --
     // check for cyclic dependencies
     for (AstRelation* cur : program.getRelations()) {
         size_t scc = sccGraph.getSCC(cur);
         if (sccGraph.isRecursive(scc)) {
             for (const AstRelation* cyclicRelation : sccGraph.getInternalRelations(scc)) {
                 // Negations and aggregations need to be stratified
                 const AstLiteral* foundLiteral = nullptr;
                 bool hasNegation = hasClauseWithNegatedRelation(cyclicRelation, cur, &program, foundLiteral);
                 if (hasNegation ||
                         hasClauseWithAggregatedRelation(cyclicRelation, cur, &program, foundLiteral)) {
                     auto const& relSet = sccGraph.getInternalRelations(scc);
                     std::set<const AstRelation*, AstNameComparison> sortedRelSet(
                             relSet.begin(), relSet.end());
                     // Negations and aggregations need to be stratified
                     std::string relationsListStr = toString(join(sortedRelSet, ",",
                             [](std::ostream& out, const AstRelation* r) { out << r->getQualifiedName(); }));
                     std::vector<DiagnosticMessage> messages;
                     messages.push_back(DiagnosticMessage(
                             "Relation " + toString(cur->getQualifiedName()), cur->getSrcLoc()));
                     std::string negOrAgg = hasNegation ? "negation" : "aggregation";
                     messages.push_back(
                             DiagnosticMessage("has cyclic " + negOrAgg, foundLiteral->getSrcLoc()));
                     report.addDiagnostic(Diagnostic(Diagnostic::ERROR,
                             DiagnosticMessage("Unable to stratify relation(s) {" + relationsListStr + "}"),
                             messages));
                     break;
                 }
             }
         }
     }
 }
Member Function Documentation
checkAggregator()
void souffle::AstSemanticCheckerImpl::checkAggregator (const AstAggregator & aggregator) private
Definition at line 604 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstClause::addToBody(), checkLiteral(), souffle::AstLiteral::clone(), souffle::AstAggregator::getBodyLiterals(), souffle::AstTranslationUnit::getErrorReport(), souffle::AstTranslationUnit::getProgram(), souffle::AstNode::getSrcLoc(), isDependent(), and souffle::visitDepthFirst().
Referenced by checkArgument().
{
     auto& report = tu.getErrorReport();
     auto& program = *tu.getProgram();
     const AstAggregator* inner = nullptr;
     // check for disallowed nested aggregates
     visitDepthFirst(aggregator, [&](const AstAggregator& innerAgg) {
         if (aggregator != innerAgg) {
             inner = &innerAgg;
         }
     });
     if (inner != nullptr) {
         report.addError("Unsupported nested aggregate", inner->getSrcLoc());
     }
     AstClause dummyClauseAggregator;
     visitDepthFirst(program, [&](const AstLiteral& parentLiteral) {
         visitDepthFirst(parentLiteral, [&](const AstAggregator& candidateAggregate) {
             if (candidateAggregate != aggregator) {
                 return;
             }
             // Get the literal containing the aggregator and put it into a dummy clause
             // so we can get information about groundedness
             dummyClauseAggregator.addToBody(std::unique_ptr<AstLiteral>(parentLiteral.clone()));
         });
     });
     visitDepthFirst(program, [&](const AstLiteral& parentLiteral) {
         visitDepthFirst(parentLiteral, [&](const AstAggregator& /* otherAggregate */) {
             // Create the other aggregate's dummy clause
             AstClause dummyClauseOther;
             dummyClauseOther.addToBody(std::unique_ptr<AstLiteral>(parentLiteral.clone()));
             // Check dependency between the aggregator and this one
             if (isDependent(dummyClauseAggregator, dummyClauseOther) &&
                     isDependent(dummyClauseOther, dummyClauseAggregator)) {
                 report.addError("Mutually dependent aggregate", aggregator.getSrcLoc());
             }
         });
     });
     for (AstLiteral* literal : aggregator.getBodyLiterals()) {
         checkLiteral(*literal);
     }
 }
checkArgument()
void souffle::AstSemanticCheckerImpl::checkArgument (const AstArgument & arg) private
Definition at line 651 of file AstSemanticChecker.cpp.
References checkAggregator().
Referenced by checkAtom(), and checkLiteral().
{
     if (const auto* agg = dynamic_cast<const AstAggregator*>(&arg)) {
         checkAggregator(*agg);
     } else if (const auto* func = dynamic_cast<const AstFunctor*>(&arg)) {
         for (auto arg : func->getArguments()) {
             checkArgument(*arg);
         }
     }
 }
checkAtom()
void souffle::AstSemanticCheckerImpl::checkAtom (const AstAtom & atom) private
Definition at line 481 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), checkArgument(), souffle::AstAtom::getArguments(), souffle::AstAtom::getArity(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), souffle::AstNode::getSrcLoc(), and souffle::toString().
Referenced by checkClause(), and checkLiteral().
{
     // check existence of relation
     auto* r = getRelation(program, atom.getQualifiedName());
     if (r == nullptr) {
         report.addError("Undefined relation " + toString(atom.getQualifiedName()), atom.getSrcLoc());
     }
     // check arity
     if ((r != nullptr) && r->getArity() != atom.getArity()) {
         report.addError(
                 "Mismatching arity of relation " + toString(atom.getQualifiedName()), atom.getSrcLoc());
     }
     for (const AstArgument* arg : atom.getArguments()) {
         checkArgument(*arg);
     }
 }
checkClause()
void souffle::AstSemanticCheckerImpl::checkClause (const AstClause & clause) private
Definition at line 723 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ErrorReport::addWarning(), checkAtom(), checkFact(), checkLiteral(), souffle::contains(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getExecutionPlan(), souffle::AstClause::getHead(), souffle::AstVariable::getName(), souffle::AstExecutionPlan::getOrders(), souffle::AstNode::getSrcLoc(), souffle::hasUnnamedVariable(), i, souffle::isFact(), souffle::RecursiveClauses::recursive(), and souffle::visitDepthFirst().
Referenced by AstSemanticCheckerImpl().
{
     // check head atom
     checkAtom(*clause.getHead());
     // check for absence of underscores in head
     if (hasUnnamedVariable(clause.getHead())) {
         report.addError("Underscore in head of rule", clause.getHead()->getSrcLoc());
     }
     // check body literals
     for (AstLiteral* lit : clause.getBodyLiterals()) {
         checkLiteral(*lit);
     }
     // check facts
     if (isFact(clause)) {
         checkFact(clause);
     }
     // check whether named unnamed variables of the form _<ident>
     // are only used once in a clause; if not, warnings will be
     // issued.
     std::map<std::string, int> var_count;
     std::map<std::string, const AstVariable*> var_pos;
     visitDepthFirst(clause, [&](const AstVariable& var) {
         var_count[var.getName()]++;
         var_pos[var.getName()] = &var;
     });
     for (const auto& cur : var_count) {
         int numAppearances = cur.second;
         const auto& varName = cur.first;
         const auto& varLocation = var_pos[varName]->getSrcLoc();
         if (varName[0] == '_') {
             assert(varName.size() > 1 && "named variable should not be a single underscore");
             if (numAppearances > 1) {
                 report.addWarning("Variable " + varName + " marked as singleton but occurs more than once",
                         varLocation);
             }
         }
     }
     // check execution plan
     if (clause.getExecutionPlan() != nullptr) {
         auto numAtoms = getBodyLiterals<AstAtom>(clause).size();
         for (const auto& cur : clause.getExecutionPlan()->getOrders()) {
             bool isComplete = true;
             auto order = cur.second->getOrder();
             for (unsigned i = 1; i <= order.size(); i++) {
                 if (!contains(order, i)) {
                     isComplete = false;
                     break;
                 }
             }
             if (order.size() != numAtoms || !isComplete) {
                 report.addError("Invalid execution order in plan", cur.second->getSrcLoc());
             }
         }
     }
     // check auto-increment
     if (recursiveClauses.recursive(&clause)) {
         visitDepthFirst(clause, [&](const AstCounter& ctr) {
             report.addError("Auto-increment functor in a recursive rule", ctr.getSrcLoc());
         });
     }
 }
checkComplexRule()
void souffle::AstSemanticCheckerImpl::checkComplexRule (std::set< const AstClause *> multiRule) private
Definition at line 790 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addWarning(), souffle::getBodyLiterals(), souffle::AstVariable::getName(), and souffle::visitDepthFirst().
Referenced by AstSemanticCheckerImpl().
{
     std::map<std::string, int> var_count;
     std::map<std::string, const AstVariable*> var_pos;
     // Count the variable occurrence for the body of a
     // complex rule only once.
     // TODO (b-scholz): for negation / disjunction this is not quite
     // right; we would need more semantic information here.
     for (auto literal : (*multiRule.begin())->getBodyLiterals()) {
         visitDepthFirst(*literal, [&](const AstVariable& var) {
             var_count[var.getName()]++;
             var_pos[var.getName()] = &var;
         });
     }
     // Count variable occurrence for each head separately
     for (auto clause : multiRule) {
         visitDepthFirst(*(clause->getHead()), [&](const AstVariable& var) {
             var_count[var.getName()]++;
             var_pos[var.getName()] = &var;
         });
     }
     // Check that a variables occurs more than once
     for (const auto& cur : var_count) {
         int numAppearances = cur.second;
         const auto& varName = cur.first;
         const auto& varLocation = var_pos[varName]->getSrcLoc();
         if (varName[0] != '_' && numAppearances == 1) {
             report.addWarning("Variable " + varName + " only occurs once", varLocation);
         }
     }
 }
checkConstant()
void souffle::AstSemanticCheckerImpl::checkConstant (const AstArgument & argument) private
Definition at line 677 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::fatal(), souffle::AstNode::getSrcLoc(), and souffle::isConstantArithExpr().
Referenced by checkFact().
{
     if (const auto* var = dynamic_cast<const AstVariable*>(&argument)) {
         report.addError("Variable " + var->getName() + " in fact", var->getSrcLoc());
     } else if (dynamic_cast<const AstUnnamedVariable*>(&argument) != nullptr) {
         report.addError("Underscore in fact", argument.getSrcLoc());
     } else if (dynamic_cast<const AstIntrinsicFunctor*>(&argument) != nullptr) {
         if (!isConstantArithExpr(argument)) {
             report.addError("Function in fact", argument.getSrcLoc());
         }
     } else if (dynamic_cast<const AstUserDefinedFunctor*>(&argument) != nullptr) {
         report.addError("User-defined functor in fact", argument.getSrcLoc());
     } else if (auto* cast = dynamic_cast<const AstTypeCast*>(&argument)) {
         checkConstant(*cast->getValue());
     } else if (dynamic_cast<const AstCounter*>(&argument) != nullptr) {
         report.addError("Counter in fact", argument.getSrcLoc());
     } else if (dynamic_cast<const AstConstant*>(&argument) != nullptr) {
         // this one is fine - type checker will make sure of number and symbol constants
     } else if (auto* ri = dynamic_cast<const AstRecordInit*>(&argument)) {
         for (auto* arg : ri->getArguments()) {
             checkConstant(*arg);
         }
     } else {
         fatal("unsupported argument type: %s", typeid(argument).name());
     }
 }
checkFact()
void souffle::AstSemanticCheckerImpl::checkFact (const AstClause & fact) private
Definition at line 704 of file AstSemanticChecker.cpp.
References checkConstant(), souffle::AstAtom::getArguments(), souffle::AstClause::getHead(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), and souffle::isFact().
Referenced by checkClause().
{
     assert(isFact(fact));
     AstAtom* head = fact.getHead();
     if (head == nullptr) {
         return;  // checked by clause
     }
     AstRelation* rel = getRelation(program, head->getQualifiedName());
     if (rel == nullptr) {
         return;  // checked by clause
     }
     // facts must only contain constants
     for (auto arg : head->getArguments()) {
         checkConstant(*arg);
     }
 }
checkInlining()
void souffle::AstSemanticCheckerImpl::checkInlining () private
Definition at line 1228 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::findInlineCycle(), souffle::AstNegation::getAtom(), souffle::AstNode::getChildNodes(), souffle::getClauses(), souffle::AstAtom::getQualifiedName(), souffle::AstRelation::getQualifiedName(), souffle::getRelation(), souffle::AstProgram::getRelations(), souffle::AstNode::getSrcLoc(), i, souffle::INLINE, souffle::IOType::isIO(), relation, souffle::toString(), and souffle::visitDepthFirst().
Referenced by AstSemanticCheckerImpl().
{
     auto isInline = [&](const AstRelation* rel) { return rel->hasQualifier(RelationQualifier::INLINE); };
     // Find all inlined relations
     AstRelationSet inlinedRelations;
     for (const auto& relation : program.getRelations()) {
         if (isInline(relation)) {
             inlinedRelations.insert(relation);
             if (ioTypes.isIO(relation)) {
                 report.addError(
                         "IO relation " + toString(relation->getQualifiedName()) + " cannot be inlined",
                         relation->getSrcLoc());
             }
         }
     }
     // Check 1:
     // Let G' be the subgraph of the precedence graph G containing only those nodes
     // which are marked with the inline directive.
     // If G' contains a cycle, then inlining cannot be performed.
     AstRelationSet unvisited;  // nodes that have not been visited yet
     AstRelationSet visiting;   // nodes that we are currently visiting
     AstRelationSet visited;    // nodes that have been completely explored
     // All nodes are initially unvisited
     for (const AstRelation* rel : inlinedRelations) {
         unvisited.insert(rel);
     }
     // Remember the parent node of each visited node to construct the found cycle
     std::map<const AstRelation*, const AstRelation*> origins;
     std::vector<AstQualifiedName> result =
             findInlineCycle(precedenceGraph, origins, nullptr, unvisited, visiting, visited);
     // If the result contains anything, then a cycle was found
     if (!result.empty()) {
         AstRelation* cycleOrigin = getRelation(program, result[result.size() - 1]);
         // Construct the string representation of the cycle
         std::stringstream cycle;
         cycle << "{" << cycleOrigin->getQualifiedName();
         // Print it backwards to preserve the initial cycle order
         for (int i = result.size() - 2; i >= 0; i--) {
             cycle << ", " << result[i];
         }
         cycle << "}";
         report.addError(
                 "Cannot inline cyclically dependent relations " + cycle.str(), cycleOrigin->getSrcLoc());
     }
     // Check 2:
     // Cannot use the counter argument ('$') in inlined relations
     // Check if an inlined literal ever takes in a $
     visitDepthFirst(program, [&](const AstAtom& atom) {
         AstRelation* associatedRelation = getRelation(program, atom.getQualifiedName());
         if (associatedRelation != nullptr && isInline(associatedRelation)) {
             visitDepthFirst(atom, [&](const AstArgument& arg) {
                 if (dynamic_cast<const AstCounter*>(&arg) != nullptr) {
                     report.addError(
                             "Cannot inline literal containing a counter argument '$'", arg.getSrcLoc());
                 }
             });
         }
     });
     // Check if an inlined clause ever contains a $
     for (const AstRelation* rel : inlinedRelations) {
         for (AstClause* clause : getClauses(program, *rel)) {
             visitDepthFirst(*clause, [&](const AstArgument& arg) {
                 if (dynamic_cast<const AstCounter*>(&arg) != nullptr) {
                     report.addError(
                             "Cannot inline clause containing a counter argument '$'", arg.getSrcLoc());
                 }
             });
         }
     }
     // Check 3:
     // Suppose the relation b is marked with the inline directive, but appears negated
     // in a clause. Then, if b introduces a new variable in its body, we cannot inline
     // the relation b.
     // Find all relations with the inline declarative that introduce new variables in their bodies
     AstRelationSet nonNegatableRelations;
     for (const AstRelation* rel : inlinedRelations) {
         bool foundNonNegatable = false;
         for (const AstClause* clause : getClauses(program, *rel)) {
             // Get the variables in the head
             std::set<std::string> headVariables;
             visitDepthFirst(
                     *clause->getHead(), [&](const AstVariable& var) { headVariables.insert(var.getName()); });
             // Get the variables in the body
             std::set<std::string> bodyVariables;
             visitDepthFirst(clause->getBodyLiterals(),
                     [&](const AstVariable& var) { bodyVariables.insert(var.getName()); });
             // Check if all body variables are in the head
             // Do this separately to the above so only one error is printed per variable
             for (const std::string& var : bodyVariables) {
                 if (headVariables.find(var) == headVariables.end()) {
                     nonNegatableRelations.insert(rel);
                     foundNonNegatable = true;
                     break;
                 }
             }
             if (foundNonNegatable) {
                 break;
             }
         }
     }
     // Check that these relations never appear negated
     visitDepthFirst(program, [&](const AstNegation& neg) {
         AstRelation* associatedRelation = getRelation(program, neg.getAtom()->getQualifiedName());
         if (associatedRelation != nullptr &&
                 nonNegatableRelations.find(associatedRelation) != nonNegatableRelations.end()) {
             report.addError(
                     "Cannot inline negated relation which may introduce new variables", neg.getSrcLoc());
         }
     });
     // Check 4:
     // Don't support inlining atoms within aggregators at this point.
     // Reasoning: Suppose we have an aggregator like `max X: a(X)`, where `a` is inlined to `a1` and `a2`.
     // Then, `max X: a(X)` will become `max( max X: a1(X),  max X: a2(X) )`. Suppose further that a(X) has
     // values X where it is true, while a2(X) does not. Then, the produced argument
     // `max( max X: a1(X),  max X: a2(X) )` will not return anything (as one of its arguments fails), while
     // `max X: a(X)` will.
     // Can work around this with emptiness checks (e.g. `!a1(_), ... ; !a2(_), ... ; ...`)
     // This corner case prevents generalising aggregator inlining with the current set up.
     visitDepthFirst(program, [&](const AstAggregator& aggr) {
         visitDepthFirst(aggr, [&](const AstAtom& subatom) {
             const AstRelation* rel = getRelation(program, subatom.getQualifiedName());
             if (rel != nullptr && isInline(rel)) {
                 report.addError("Cannot inline relations that appear in aggregator", subatom.getSrcLoc());
             }
         });
     });
     // Check 5:
     // Suppose a relation `a` is inlined, appears negated in a clause, and contains a
     // (possibly nested) unnamed variable in its arguments. Then, the atom can't be
     // inlined, as unnamed variables are named during inlining (since they may appear
     // multiple times in an inlined-clause's body) => ungroundedness!
     // Exception: It's fine if the unnamed variable appears in a nested aggregator, as
     // the entire aggregator will automatically be grounded.
     // TODO (azreika): special case where all rules defined for `a` use the
     // underscored-argument exactly once: can workaround by remapping the variable
     // back to an underscore - involves changes to the actual inlining algo, though
     // Returns the pair (isValid, lastSrcLoc) where:
     //  - isValid is true if and only if the node contains an invalid underscore, and
     //  - lastSrcLoc is the source location of the last visited node
     std::function<std::pair<bool, SrcLocation>(const AstNode*)> checkInvalidUnderscore =
             [&](const AstNode* node) {
                 if (dynamic_cast<const AstUnnamedVariable*>(node) != nullptr) {
                     // Found an invalid underscore
                     return std::make_pair(true, node->getSrcLoc());
                 } else if (dynamic_cast<const AstAggregator*>(node) != nullptr) {
                     // Don't care about underscores within aggregators
                     return std::make_pair(false, node->getSrcLoc());
                 }
                 // Check if any children nodes use invalid underscores
                 for (const AstNode* child : node->getChildNodes()) {
                     std::pair<bool, SrcLocation> childStatus = checkInvalidUnderscore(child);
                     if (childStatus.first) {
                         // Found an invalid underscore
                         return childStatus;
                     }
                 }
                 return std::make_pair(false, node->getSrcLoc());
             };
     // Perform the check
     visitDepthFirst(program, [&](const AstNegation& negation) {
         const AstAtom* associatedAtom = negation.getAtom();
         const AstRelation* associatedRelation = getRelation(program, associatedAtom->getQualifiedName());
         if (associatedRelation != nullptr && isInline(associatedRelation)) {
             std::pair<bool, SrcLocation> atomStatus = checkInvalidUnderscore(associatedAtom);
             if (atomStatus.first) {
                 report.addError(
                         "Cannot inline negated atom containing an unnamed variable unless the variable is "
                         "within an aggregator",
                         atomStatus.second);
             }
         }
     });
 }
checkIO()
void souffle::AstSemanticCheckerImpl::checkIO () private
Definition at line 986 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstProgram::getIOs(), souffle::getRelation(), and souffle::toString().
Referenced by AstSemanticCheckerImpl().
{
     auto checkIO = [&](const AstIO* directive) {
         auto* r = getRelation(program, directive->getQualifiedName());
         if (r == nullptr) {
             report.addError(
                     "Undefined relation " + toString(directive->getQualifiedName()), directive->getSrcLoc());
         }
     };
     for (const auto* directive : program.getIOs()) {
         checkIO(directive);
     }
 }
checkLiteral()
void souffle::AstSemanticCheckerImpl::checkLiteral (const AstLiteral & literal) private
Definition at line 546 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), checkArgument(), checkAtom(), souffle::fatal(), souffle::AstNode::getSrcLoc(), and souffle::hasUnnamedVariable().
Referenced by checkAggregator(), and checkClause().
{
     // check potential nested atom
     if (const auto* atom = dynamic_cast<const AstAtom*>(&literal)) {
         checkAtom(*atom);
     }
     if (const auto* neg = dynamic_cast<const AstNegation*>(&literal)) {
         checkAtom(*neg->getAtom());
     }
     if (const auto* constraint = dynamic_cast<const AstBinaryConstraint*>(&literal)) {
         checkArgument(*constraint->getLHS());
         checkArgument(*constraint->getRHS());
     }
     // check for invalid underscore utilization
     if (hasUnnamedVariable(&literal)) {
         if (dynamic_cast<const AstAtom*>(&literal) != nullptr) {
             // nothing to check since underscores are allowed
         } else if (dynamic_cast<const AstNegation*>(&literal) != nullptr) {
             // nothing to check since underscores are allowed
         } else if (dynamic_cast<const AstBinaryConstraint*>(&literal) != nullptr) {
             report.addError("Underscore in binary relation", literal.getSrcLoc());
         } else {
             fatal("unsupported literal type: %s", typeid(literal).name());
         }
     }
 }
checkNamespaces()
void souffle::AstSemanticCheckerImpl::checkNamespaces () private
Definition at line 1433 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstProgram::getRelations(), souffle::AstProgram::getTypes(), and souffle::toString().
Referenced by AstSemanticCheckerImpl().
{
     std::map<std::string, SrcLocation> names;
     // Find all names and report redeclarations as we go.
     for (const auto& type : program.getTypes()) {
         const std::string name = toString(type->getQualifiedName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on type " + name, type->getSrcLoc());
         } else {
             names[name] = type->getSrcLoc();
         }
     }
     for (const auto& rel : program.getRelations()) {
         const std::string name = toString(rel->getQualifiedName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on relation " + name, rel->getSrcLoc());
         } else {
             names[name] = rel->getSrcLoc();
         }
     }
 }
checkRecordType()
void souffle::AstSemanticCheckerImpl::checkRecordType (const AstRecordType & type) private
Definition at line 921 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::AstRecordType::getFields(), souffle::getName, souffle::AstType::getQualifiedName(), i, souffle::TypeEnvironment::isType(), and j.
Referenced by checkType().
{
     auto&& fields = type.getFields();
     // check proper definition of all field types
     for (auto&& field : fields) {
         if (!typeEnv.isType(field->getTypeName())) {
             report.addError(tfm::format("Undefined type %s in definition of field %s", field->getTypeName(),
                                     field->getName()),
                     field->getSrcLoc());
         }
     }
     // check that field names are unique
     for (std::size_t i = 0; i < fields.size(); i++) {
         auto&& cur_name = fields[i]->getName();
         for (std::size_t j = 0; j < i; j++) {
             if (fields[j]->getName() == cur_name) {
                 report.addError(tfm::format("Doubly defined field name %s in definition of type %s", cur_name,
                                         type.getQualifiedName()),
                         fields[i]->getSrcLoc());
             }
         }
     }
 }
checkRelation()
void souffle::AstSemanticCheckerImpl::checkRelation (const AstRelation & relation) private
Definition at line 846 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ErrorReport::addWarning(), checkRelationDeclaration(), souffle::EQREL, souffle::AstRelation::getArity(), souffle::AstRelation::getAttributes(), souffle::getClauses(), souffle::AstRelation::getQualifiedName(), souffle::AstRelation::getRepresentation(), souffle::AstNode::getSrcLoc(), souffle::AstRelation::hasQualifier(), souffle::IOType::isInput(), souffle::SUPPRESSED, and souffle::toString().
Referenced by AstSemanticCheckerImpl().
{
     if (relation.getRepresentation() == RelationRepresentation::EQREL) {
         if (relation.getArity() == 2) {
             const auto& attributes = relation.getAttributes();
             assert(attributes.size() == 2 && "mismatching attribute size and arity");
             if (attributes[0]->getTypeName() != attributes[1]->getTypeName()) {
                 report.addError("Domains of equivalence relation " + toString(relation.getQualifiedName()) +
                                         " are different",
                         relation.getSrcLoc());
             }
         } else {
             report.addError(
                     "Equivalence relation " + toString(relation.getQualifiedName()) + " is not binary",
                     relation.getSrcLoc());
         }
     }
     // start with declaration
     checkRelationDeclaration(relation);
     // check whether this relation is empty
     if (getClauses(program, relation).empty() && !ioTypes.isInput(&relation) &&
             !relation.hasQualifier(RelationQualifier::SUPPRESSED)) {
         report.addWarning("No rules/facts defined for relation " + toString(relation.getQualifiedName()),
                 relation.getSrcLoc());
     }
 }
checkRelationDeclaration()
void souffle::AstSemanticCheckerImpl::checkRelationDeclaration (const AstRelation & relation) private
Definition at line 824 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::AstRelation::getArity(), souffle::AstRelation::getAttributes(), souffle::AstAttribute::getName(), souffle::AstNode::getSrcLoc(), souffle::getType(), souffle::AstAttribute::getTypeName(), i, souffle::TypeEnvironment::isPrimitiveType(), and j.
Referenced by checkRelation().
{
     const auto& attributes = relation.getAttributes();
     assert(attributes.size() == relation.getArity() && "mismatching attribute size and arity");
     for (size_t i = 0; i < relation.getArity(); i++) {
         AstAttribute* attr = attributes[i];
         auto&& typeName = attr->getTypeName();
         /* check whether type exists */
         if (!typeEnv.isPrimitiveType(typeName) && !getType(program, typeName)) {
             report.addError(tfm::format("Undefined type in attribute %s", *attr), attr->getSrcLoc());
         }
         /* check whether name occurs more than once */
         for (size_t j = 0; j < i; j++) {
             if (attr->getName() == attributes[j]->getName()) {
                 report.addError(tfm::format("Doubly defined attribute name %s", *attr), attr->getSrcLoc());
             }
         }
     }
 }
checkSubsetType()
void souffle::AstSemanticCheckerImpl::checkSubsetType (const AstSubsetType & type) private
Definition at line 945 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::AstSubsetType::getBaseType(), souffle::AstType::getQualifiedName(), souffle::AstNode::getSrcLoc(), souffle::TypeEnvironment::getType(), souffle::TypeEnvironmentAnalysis::isCyclic(), and souffle::TypeEnvironment::isType().
Referenced by checkType().
{
     if (typeEnvAnalysis.isCyclic(astType.getQualifiedName())) {
         report.addError(
                 tfm::format("Infinite descent in the definition of type %s", astType.getQualifiedName()),
                 astType.getSrcLoc());
         return;
     }
     if (!typeEnv.isType(astType.getBaseType())) {
         report.addError(tfm::format("Undefined base type %s in definition of type %s", astType.getBaseType(),
                                 astType.getQualifiedName()),
                 astType.getSrcLoc());
         return;
     }
     auto& rootType = typeEnv.getType(astType.getBaseType());
     if (isA<UnionType>(rootType)) {
         report.addError(tfm::format("Subset type %s can't be derived from union %s",
                                 astType.getQualifiedName(), rootType.getName()),
                 astType.getSrcLoc());
     }
 }
checkType()
void souffle::AstSemanticCheckerImpl::checkType (const AstType & type) private
Definition at line 969 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), checkRecordType(), checkSubsetType(), checkUnionType(), souffle::fatal(), souffle::AstType::getQualifiedName(), souffle::AstNode::getSrcLoc(), and souffle::TypeEnvironment::isPrimitiveType().
Referenced by AstSemanticCheckerImpl().
{
     if (typeEnv.isPrimitiveType(type.getQualifiedName())) {
         report.addError("Redefinition of the predefined type", type.getSrcLoc());
         return;
     }
     if (isA<AstUnionType>(type)) {
         checkUnionType(*as<AstUnionType>(type));
     } else if (isA<AstRecordType>(type)) {
         checkRecordType(*as<AstRecordType>(type));
     } else if (isA<AstSubsetType>(type)) {
         checkSubsetType(*as<AstSubsetType>(type));
     } else {
         fatal("unsupported type construct: %s", typeid(type).name());
     }
 }
checkUnionType()
void souffle::AstSemanticCheckerImpl::checkUnionType (const AstUnionType & type) private
Definition at line 876 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::TypeEnvironmentAnalysis::getPrimitiveTypesInUnion(), souffle::AstType::getQualifiedName(), souffle::AstNode::getSrcLoc(), souffle::getType(), souffle::AstProgram::getTypes(), souffle::AstUnionType::getTypes(), souffle::TypeEnvironmentAnalysis::isCyclic(), souffle::TypeEnvironment::isPrimitiveType(), souffle::join(), souffle::sub(), and souffle::toString().
Referenced by checkType().
{
     // check presence of all the element types and that all element types are based off a primitive
     for (const AstQualifiedName& sub : type.getTypes()) {
         if (typeEnv.isPrimitiveType(sub)) {
             continue;
         }
         const AstType* subt = getType(program, sub);
         if (subt == nullptr) {
             report.addError("Undefined type " + toString(sub) + " in definition of union type " +
                                     toString(type.getQualifiedName()),
                     type.getSrcLoc());
         } else if (!isA<AstUnionType>(subt) && !isA<AstSubsetType>(subt)) {
             report.addError(tfm::format("Union type %s contains the non-primitive type %s",
                                     type.getQualifiedName(), sub),
                     type.getSrcLoc());
         }
     }
     // Check if the union is recursive.
     if (typeEnvAnalysis.isCyclic(type.getQualifiedName())) {
         report.addError("Infinite descent in the definition of type " + toString(type.getQualifiedName()),
                 type.getSrcLoc());
     }
     /* check that union types do not mix different primitive types */
     for (const auto* type : program.getTypes()) {
         // We are only interested in unions here.
         if (dynamic_cast<const AstUnionType*>(type) == nullptr) {
             continue;
         }
         const auto& name = type->getQualifiedName();
         const auto& predefinedTypesInUnion = typeEnvAnalysis.getPrimitiveTypesInUnion(name);
         // Report error (if size == 0, then the union is cyclic)
         if (predefinedTypesInUnion.size() > 1) {
             report.addError(
                     tfm::format("Union type %s is defined over {%s} (multiple primitive types in union)",
                             name, join(predefinedTypesInUnion, ", ")),
                     type->getSrcLoc());
         }
     }
 }
checkWitnessProblem()
void souffle::AstSemanticCheckerImpl::checkWitnessProblem () private
Definition at line 1121 of file AstSemanticChecker.cpp.
References souffle::AstAtom::addArgument(), souffle::ErrorReport::addError(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::usesInvalidWitness(), and souffle::visitDepthFirst().
Referenced by AstSemanticCheckerImpl().
{
     // Visit each clause to check if an invalid aggregator witness is used
     visitDepthFirst(program, [&](const AstClause& clause) {
         // Body literals of the clause to check
         std::vector<AstLiteral*> bodyLiterals = clause.getBodyLiterals();
         // Add in all head variables as new ungrounded body literals
         auto headVariables = std::make_unique<AstAtom>("*");
         visitDepthFirst(*clause.getHead(), [&](const AstVariable& var) {
             headVariables->addArgument(std::unique_ptr<AstVariable>(var.clone()));
         });
         auto headNegation = std::make_unique<AstNegation>(std::move(headVariables));
         bodyLiterals.push_back(headNegation.get());
         // Perform the check
         std::set<std::unique_ptr<AstArgument>> groundedArguments;
         for (auto&& invalidArgument : usesInvalidWitness(tu, bodyLiterals, groundedArguments)) {
             report.addError(
                     "Witness problem: argument grounded by an aggregator's inner scope is used ungrounded in "
                     "outer scope",
                     invalidArgument);
         }
     });
 }
isDependent()
bool souffle::AstSemanticCheckerImpl::isDependent (const AstClause & agg1, const AstClause & agg2) private
agg1, agg2 are clauses which contain no head, and consist of a single literal that contains an aggregate.
agg1 is dependent on agg2 if agg1 contains a variable which is grounded by agg2, and not by agg1.
Definition at line 579 of file AstSemanticChecker.cpp.
References souffle::getGroundedTerms(), and souffle::visitDepthFirst().
Referenced by checkAggregator().
{
     auto groundedInAgg1 = getGroundedTerms(tu, agg1);
     auto groundedInAgg2 = getGroundedTerms(tu, agg2);
     bool dependent = false;
     // For each variable X in the first aggregate
     visitDepthFirst(agg1, [&](const AstVariable& searchVar) {
         // Try to find the corresponding variable X in the second aggregate
         // by string comparison
         const AstVariable* matchingVarPtr = nullptr;
         visitDepthFirst(agg2, [&](const AstVariable& var) {
             if (var == searchVar) {
                 matchingVarPtr = &var;
                 return;
             }
         });
         // If the variable occurs in both clauses (a match was found)
         if (matchingVarPtr != nullptr) {
             if (!groundedInAgg1[&searchVar] && groundedInAgg2[matchingVarPtr]) {
                 dependent = true;
             }
         }
     });
     return dependent;
 }
Field Documentation
ioTypes
const IOType& souffle::AstSemanticCheckerImpl::ioTypes = *tu.getAnalysis<IOType>() private
Definition at line 73 of file AstSemanticChecker.cpp.
precedenceGraph
const PrecedenceGraph& souffle::AstSemanticCheckerImpl::precedenceGraph = *tu.getAnalysis<PrecedenceGraph>() private
Definition at line 74 of file AstSemanticChecker.cpp.
program
const AstProgram& souffle::AstSemanticCheckerImpl::program = *tu.getProgram() private
Definition at line 81 of file AstSemanticChecker.cpp.
recursiveClauses
const RecursiveClauses& souffle::AstSemanticCheckerImpl::recursiveClauses = *tu.getAnalysis<RecursiveClauses>() private
Definition at line 75 of file AstSemanticChecker.cpp.
report
ErrorReport& souffle::AstSemanticCheckerImpl::report = tu.getErrorReport() private
Definition at line 82 of file AstSemanticChecker.cpp.
sccGraph
const SCCGraph& souffle::AstSemanticCheckerImpl::sccGraph = *tu.getAnalysis<SCCGraph>() private
Definition at line 78 of file AstSemanticChecker.cpp.
tu
AstTranslationUnit& souffle::AstSemanticCheckerImpl::tu
Definition at line 69 of file AstSemanticChecker.cpp.
typeAnalysis
const TypeAnalysis& souffle::AstSemanticCheckerImpl::typeAnalysis = *tu.getAnalysis<TypeAnalysis>() private
Definition at line 76 of file AstSemanticChecker.cpp.
typeEnv
const TypeEnvironment& souffle::AstSemanticCheckerImpl::typeEnv = typeEnvAnalysis.getTypeEnvironment() private
Definition at line 80 of file AstSemanticChecker.cpp.
typeEnvAnalysis
const TypeEnvironmentAnalysis& souffle::AstSemanticCheckerImpl::typeEnvAnalysis = *tu.getAnalysis<TypeEnvironmentAnalysis>() private
Definition at line 77 of file AstSemanticChecker.cpp.
The documentation for this struct was generated from the following file:
AstSemanticChecker.cpp